
Clotch_Armor = ['HEAD_CLOTH_SET1','HEAD_CLOTH_SET3','HEAD_CLOTH_SET2',
                'HEAD_CLOTH_KEEPER','HEAD_CLOTH_ROYAL','HEAD_CLOTH_HELL',
                'HEAD_CLOTH_MORGANA','HEAD_CLOTH_AVALON','HEAD_CLOTH_FEY',
                
                'ARMOR_CLOTH_SET1','ARMOR_CLOTH_SET3','ARMOR_CLOTH_SET2',
                'ARMOR_CLOTH_KEEPER','ARMOR_CLOTH_ROYAL','ARMOR_CLOTH_HELL',
                'ARMOR_CLOTH_MORGANA','ARMOR_CLOTH_AVALON','ARMOR_CLOTH_FEY',
                
                'SHOES_CLOTH_SET1','SHOES_CLOTH_SET3','SHOES_CLOTH_SET2',
                'SHOES_CLOTH_KEEPER','SHOES_CLOTH_ROYAL','SHOES_CLOTH_HELL',
                'SHOES_CLOTH_MORGANA','SHOES_CLOTH_AVALON','SHOES_CLOTH_FEY']

Plate_Armor = ['HEAD_PLATE_SET1','HEAD_PLATE_SET2','HEAD_PLATE_SET3',
                'HEAD_PLATE_UNDEAD','HEAD_PLATE_HELL','HEAD_PLATE_KEEPER',
                'HEAD_PLATE_ROYAL','HEAD_PLATE_AVALON','HEAD_PLATE_FEY',
                
                'ARMOR_PLATE_SET1','ARMOR_PLATE_SET3','ARMOR_PLATE_SET2',
                'ARMOR_PLATE_UNDEAD','ARMOR_PLATE_HELL','ARMOR_PLATE_KEEPER',
                'ARMOR_PLATE_ROYAL','ARMOR_PLATE_AVALON','ARMOR_PLATE_FEY',
                
                'SHOES_PLATE_SET1','SHOES_PLATE_SET3','SHOES_PLATE_SET2',
                'SHOES_PLATE_UNDEAD','SHOES_PLATE_HELL','SHOES_PLATE_KEEPER',
                'SHOES_PLATE_ROYAL','SHOES_PLATE_AVALON','SHOES_PLATE_FEY']

Leather_Armor = ['HEAD_LEATHER_SET1','HEAD_PLEATHER_SET2','HEAD_LEATHER_SET3',
                'HEAD_LEATHER_MORGANA','HEAD_LEATHER_HELL','HEAD_LEATHER_UNDEAD',
                'HEAD_LEATHER_ROYAL','HEAD_LEATHER_AVALON','HEAD_LEATHER_FEY',
                
                'ARMOR_LEATHER_SET1','ARMOR_LEATHER_SET3','ARMOR_LEATHER_SET2',
                'ARMOR_LEATHER_MORGANA','ARMOR_LEATHER_HELL','ARMOR_LEATHER_UNDEAD',
                'ARMOR_LEATHER_ROYAL','ARMOR_LEATHER_AVALON','ARMOR_LEATHER_FEY',
                
                'SHOES_LEATHER_SET1','SHOES_LEATHER_SET3','SHOES_LEATHER_SET2',
                'SHOES_LEATHER_MORGANA','SHOES_LEATHER_HELL','SHOES_LEATHER_UNDEAD',
                'SHOES_LEATHER_ROYAL','SHOES_LEATHER_AVALON','SHOES_LEATHER_FEY']

Resource = ['ORE', 'FIBER', 'WOOD', 'HIDE', 'ROCK', 'METALBAR','CLOTH', 'PLANKS', 'LEATHER', 'STONEBLOCK']

Things = ['BAG', 'BAG_INSIGHT', 'CAPE',
        'CAPEITEM_HERETIC', 'CAPEITEM_KEEPER', 'CAPEITEM_MORGANA', 'CAPEITEM_DEMON', 'CAPEITEM_UNDEAD',
        'CAPEITEM_FW_CAERLEON', 'CAPEITEM_FW_FORTSTERLING', 'CAPEITEM_FW_LYMHURST', 'CAPEITEM_FW_BRIDGEWATCH', 'CAPEITEM_FW_MARTLOCK', 'CAPEITEM_FW_THETFORD'
        ]

