from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import QButtonGroup

import webbrowser, pandas

import Sort_Data, List_item


qualities = 0


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 895)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.Main_Frame_Item = QtWidgets.QTabWidget(self.centralwidget)
        self.Main_Frame_Item.setGeometry(QtCore.QRect(320, 5, 470, 890))
        self.Main_Frame_Item.setObjectName("Main_Frame_Item")
        self.Clotch = QtWidgets.QWidget()
        self.Clotch.setObjectName("Clotch")
        self.Into_Frame_Item_1 = QtWidgets.QFrame(self.Clotch)
        self.Into_Frame_Item_1.setGeometry(QtCore.QRect(5, 5, 460, 860))
        self.Into_Frame_Item_1.setObjectName("Into_Frame_Item_1")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.Into_Frame_Item_1)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.checkBox23 = QtWidgets.QCheckBox(self.Into_Frame_Item_1)
        self.checkBox23.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("Pictures/T6_SHOES_CLOTH_ROYAL@0.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.checkBox23.setIcon(icon)
        self.checkBox23.setIconSize(QtCore.QSize(90, 90))
        self.checkBox23.setCheckable(True)
        self.checkBox23.setObjectName("checkBox23")
        self.gridLayout_2.addWidget(self.checkBox23, 7, 4, 1, 1)
        self.checkBox19 = QtWidgets.QCheckBox(self.Into_Frame_Item_1)
        self.checkBox19.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("Pictures/T6_SHOES_CLOTH_SET1@0.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.checkBox19.setIcon(icon1)
        self.checkBox19.setIconSize(QtCore.QSize(90, 90))
        self.checkBox19.setCheckable(True)
        self.checkBox19.setObjectName("checkBox19")
        self.gridLayout_2.addWidget(self.checkBox19, 3, 4, 1, 1)
        self.checkBox10 = QtWidgets.QCheckBox(self.Into_Frame_Item_1)
        self.checkBox10.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("Pictures/T6_ARMOR_CLOTH_SET1.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.checkBox10.setIcon(icon2)
        self.checkBox10.setIconSize(QtCore.QSize(90, 90))
        self.checkBox10.setCheckable(True)
        self.checkBox10.setObjectName("checkBox10")
        self.gridLayout_2.addWidget(self.checkBox10, 3, 2, 1, 1)
        self.checkBox1 = QtWidgets.QCheckBox(self.Into_Frame_Item_1)
        self.checkBox1.setText("")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap("Pictures/T6_HEAD_CLOTH_SET1@0.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.checkBox1.setIcon(icon3)
        self.checkBox1.setIconSize(QtCore.QSize(90, 90))
        self.checkBox1.setCheckable(True)
        self.checkBox1.setObjectName("checkBox1")
        self.gridLayout_2.addWidget(self.checkBox1, 3, 0, 1, 1)
        self.checkBox15 = QtWidgets.QCheckBox(self.Into_Frame_Item_1)
        self.checkBox15.setText("")
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap("Pictures/T6_ARMOR_CLOTH_HELL@0.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.checkBox15.setIcon(icon4)
        self.checkBox15.setIconSize(QtCore.QSize(90, 90))
        self.checkBox15.setCheckable(True)
        self.checkBox15.setObjectName("checkBox15")
        self.gridLayout_2.addWidget(self.checkBox15, 8, 2, 1, 1)
        self.checkBox14 = QtWidgets.QCheckBox(self.Into_Frame_Item_1)
        self.checkBox14.setText("")
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap("Pictures/T6_ARMOR_CLOTH_ROYAL.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.checkBox14.setIcon(icon5)
        self.checkBox14.setIconSize(QtCore.QSize(90, 90))
        self.checkBox14.setCheckable(True)
        self.checkBox14.setObjectName("checkBox14")
        self.gridLayout_2.addWidget(self.checkBox14, 7, 2, 1, 1)
        self.checkBox12 = QtWidgets.QCheckBox(self.Into_Frame_Item_1)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.checkBox12.setFont(font)
        self.checkBox12.setText("")
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap("Pictures/T6_ARMOR_CLOTH_SET2.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.checkBox12.setIcon(icon6)
        self.checkBox12.setIconSize(QtCore.QSize(90, 90))
        self.checkBox12.setCheckable(True)
        self.checkBox12.setObjectName("checkBox12")
        self.gridLayout_2.addWidget(self.checkBox12, 5, 2, 1, 1)
        self.checkBox13 = QtWidgets.QCheckBox(self.Into_Frame_Item_1)
        self.checkBox13.setText("")
        icon7 = QtGui.QIcon()
        icon7.addPixmap(QtGui.QPixmap("Pictures/T6_ARMOR_CLOTH_KEEPER.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.checkBox13.setIcon(icon7)
        self.checkBox13.setIconSize(QtCore.QSize(90, 90))
        self.checkBox13.setCheckable(True)
        self.checkBox13.setObjectName("checkBox13")
        self.gridLayout_2.addWidget(self.checkBox13, 6, 2, 1, 1)
        self.checkBox18 = QtWidgets.QCheckBox(self.Into_Frame_Item_1)
        self.checkBox18.setText("")
        icon8 = QtGui.QIcon()
        icon8.addPixmap(QtGui.QPixmap("Pictures/T6_ARMOR_CLOTH_FEY@0.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.checkBox18.setIcon(icon8)
        self.checkBox18.setIconSize(QtCore.QSize(90, 90))
        self.checkBox18.setCheckable(True)
        self.checkBox18.setObjectName("checkBox18")
        self.gridLayout_2.addWidget(self.checkBox18, 11, 2, 1, 1)
        self.checkBox11 = QtWidgets.QCheckBox(self.Into_Frame_Item_1)
        self.checkBox11.setText("")
        icon9 = QtGui.QIcon()
        icon9.addPixmap(QtGui.QPixmap("Pictures/T6_ARMOR_CLOTH_SET3.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.checkBox11.setIcon(icon9)
        self.checkBox11.setIconSize(QtCore.QSize(90, 90))
        self.checkBox11.setCheckable(True)
        self.checkBox11.setObjectName("checkBox11")
        self.gridLayout_2.addWidget(self.checkBox11, 4, 2, 1, 1)
        self.checkBox17 = QtWidgets.QCheckBox(self.Into_Frame_Item_1)
        self.checkBox17.setText("")
        icon10 = QtGui.QIcon()
        icon10.addPixmap(QtGui.QPixmap("Pictures/T6_ARMOR_CLOTH_AVALON@0.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.checkBox17.setIcon(icon10)
        self.checkBox17.setIconSize(QtCore.QSize(90, 90))
        self.checkBox17.setCheckable(True)
        self.checkBox17.setObjectName("checkBox17")
        self.gridLayout_2.addWidget(self.checkBox17, 10, 2, 1, 1)
        self.checkBox16 = QtWidgets.QCheckBox(self.Into_Frame_Item_1)
        self.checkBox16.setText("")
        icon11 = QtGui.QIcon()
        icon11.addPixmap(QtGui.QPixmap("Pictures/T6_ARMOR_CLOTH_MORGANA.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.checkBox16.setIcon(icon11)
        self.checkBox16.setIconSize(QtCore.QSize(90, 90))
        self.checkBox16.setCheckable(True)
        self.checkBox16.setObjectName("checkBox16")
        self.gridLayout_2.addWidget(self.checkBox16, 9, 2, 1, 1)
        self.checkBox21 = QtWidgets.QCheckBox(self.Into_Frame_Item_1)
        self.checkBox21.setText("")
        icon12 = QtGui.QIcon()
        icon12.addPixmap(QtGui.QPixmap("Pictures/T6_SHOES_CLOTH_SET2@0.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.checkBox21.setIcon(icon12)
        self.checkBox21.setIconSize(QtCore.QSize(90, 90))
        self.checkBox21.setCheckable(True)
        self.checkBox21.setObjectName("checkBox21")
        self.gridLayout_2.addWidget(self.checkBox21, 5, 4, 1, 1)
        self.checkBox27 = QtWidgets.QCheckBox(self.Into_Frame_Item_1)
        self.checkBox27.setText("")
        icon13 = QtGui.QIcon()
        icon13.addPixmap(QtGui.QPixmap("Pictures/T6_SHOES_CLOTH_FEY@0.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.checkBox27.setIcon(icon13)
        self.checkBox27.setIconSize(QtCore.QSize(90, 90))
        self.checkBox27.setCheckable(True)
        self.checkBox27.setObjectName("checkBox27")
        self.gridLayout_2.addWidget(self.checkBox27, 11, 4, 1, 1)
        self.checkBox20 = QtWidgets.QCheckBox(self.Into_Frame_Item_1)
        self.checkBox20.setText("")
        icon14 = QtGui.QIcon()
        icon14.addPixmap(QtGui.QPixmap("Pictures/T6_SHOES_CLOTH_SET3@0.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.checkBox20.setIcon(icon14)
        self.checkBox20.setIconSize(QtCore.QSize(90, 90))
        self.checkBox20.setCheckable(True)
        self.checkBox20.setObjectName("checkBox20")
        self.gridLayout_2.addWidget(self.checkBox20, 4, 4, 1, 1)
        self.checkBox22 = QtWidgets.QCheckBox(self.Into_Frame_Item_1)
        self.checkBox22.setText("")
        icon15 = QtGui.QIcon()
        icon15.addPixmap(QtGui.QPixmap("Pictures/T6_SHOES_CLOTH_KEEPER@0.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.checkBox22.setIcon(icon15)
        self.checkBox22.setIconSize(QtCore.QSize(90, 90))
        self.checkBox22.setCheckable(True)
        self.checkBox22.setObjectName("checkBox22")
        self.gridLayout_2.addWidget(self.checkBox22, 6, 4, 1, 1)
        self.checkBox26 = QtWidgets.QCheckBox(self.Into_Frame_Item_1)
        self.checkBox26.setText("")
        icon16 = QtGui.QIcon()
        icon16.addPixmap(QtGui.QPixmap("Pictures/T6_SHOES_CLOTH_AVALON@0.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.checkBox26.setIcon(icon16)
        self.checkBox26.setIconSize(QtCore.QSize(90, 90))
        self.checkBox26.setCheckable(True)
        self.checkBox26.setObjectName("checkBox26")
        self.gridLayout_2.addWidget(self.checkBox26, 10, 4, 1, 1)
        self.checkBox7 = QtWidgets.QCheckBox(self.Into_Frame_Item_1)
        self.checkBox7.setText("")
        icon17 = QtGui.QIcon()
        icon17.addPixmap(QtGui.QPixmap("Pictures/T6_HEAD_CLOTH_MORGANA@0.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.checkBox7.setIcon(icon17)
        self.checkBox7.setIconSize(QtCore.QSize(90, 90))
        self.checkBox7.setCheckable(True)
        self.checkBox7.setObjectName("checkBox7")
        self.gridLayout_2.addWidget(self.checkBox7, 9, 0, 1, 1)
        self.checkBox24 = QtWidgets.QCheckBox(self.Into_Frame_Item_1)
        self.checkBox24.setText("")
        icon18 = QtGui.QIcon()
        icon18.addPixmap(QtGui.QPixmap("Pictures/T6_SHOES_CLOTH_HELL@0.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.checkBox24.setIcon(icon18)
        self.checkBox24.setIconSize(QtCore.QSize(90, 90))
        self.checkBox24.setCheckable(True)
        self.checkBox24.setObjectName("checkBox24")
        self.gridLayout_2.addWidget(self.checkBox24, 8, 4, 1, 1)
        self.checkBox9 = QtWidgets.QCheckBox(self.Into_Frame_Item_1)
        self.checkBox9.setText("")
        icon19 = QtGui.QIcon()
        icon19.addPixmap(QtGui.QPixmap("Pictures/T6_HEAD_CLOTH_FEY@0.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.checkBox9.setIcon(icon19)
        self.checkBox9.setIconSize(QtCore.QSize(90, 90))
        self.checkBox9.setCheckable(True)
        self.checkBox9.setObjectName("checkBox9")
        self.gridLayout_2.addWidget(self.checkBox9, 11, 0, 1, 1)
        self.checkBox6 = QtWidgets.QCheckBox(self.Into_Frame_Item_1)
        self.checkBox6.setText("")
        icon20 = QtGui.QIcon()
        icon20.addPixmap(QtGui.QPixmap("Pictures/T6_HEAD_CLOTH_HELL@0.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.checkBox6.setIcon(icon20)
        self.checkBox6.setIconSize(QtCore.QSize(90, 90))
        self.checkBox6.setCheckable(True)
        self.checkBox6.setObjectName("checkBox6")
        self.gridLayout_2.addWidget(self.checkBox6, 8, 0, 1, 1)
        self.checkBox25 = QtWidgets.QCheckBox(self.Into_Frame_Item_1)
        self.checkBox25.setText("")
        icon21 = QtGui.QIcon()
        icon21.addPixmap(QtGui.QPixmap("Pictures/T6_SHOES_CLOTH_MORGANA@0.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.checkBox25.setIcon(icon21)
        self.checkBox25.setIconSize(QtCore.QSize(90, 90))
        self.checkBox25.setCheckable(True)
        self.checkBox25.setObjectName("checkBox25")
        self.gridLayout_2.addWidget(self.checkBox25, 9, 4, 1, 1)
        self.checkBox5 = QtWidgets.QCheckBox(self.Into_Frame_Item_1)
        self.checkBox5.setText("")
        icon22 = QtGui.QIcon()
        icon22.addPixmap(QtGui.QPixmap("Pictures/T6_HEAD_CLOTH_ROYAL@0.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.checkBox5.setIcon(icon22)
        self.checkBox5.setIconSize(QtCore.QSize(90, 90))
        self.checkBox5.setCheckable(True)
        self.checkBox5.setObjectName("checkBox5")
        self.gridLayout_2.addWidget(self.checkBox5, 7, 0, 1, 1)
        self.checkBox4 = QtWidgets.QCheckBox(self.Into_Frame_Item_1)
        self.checkBox4.setText("")
        icon23 = QtGui.QIcon()
        icon23.addPixmap(QtGui.QPixmap("Pictures/T6_HEAD_CLOTH_KEEPER@0.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.checkBox4.setIcon(icon23)
        self.checkBox4.setIconSize(QtCore.QSize(90, 90))
        self.checkBox4.setCheckable(True)
        self.checkBox4.setObjectName("checkBox4")
        self.gridLayout_2.addWidget(self.checkBox4, 6, 0, 1, 1)
        self.checkBox3 = QtWidgets.QCheckBox(self.Into_Frame_Item_1)
        self.checkBox3.setText("")
        icon24 = QtGui.QIcon()
        icon24.addPixmap(QtGui.QPixmap("Pictures/T6_HEAD_CLOTH_SET2@0.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.checkBox3.setIcon(icon24)
        self.checkBox3.setIconSize(QtCore.QSize(90, 90))
        self.checkBox3.setCheckable(True)
        self.checkBox3.setObjectName("checkBox3")
        self.gridLayout_2.addWidget(self.checkBox3, 5, 0, 1, 1)
        self.checkBox8 = QtWidgets.QCheckBox(self.Into_Frame_Item_1)
        self.checkBox8.setText("")
        icon25 = QtGui.QIcon()
        icon25.addPixmap(QtGui.QPixmap("Pictures/T6_HEAD_CLOTH_AVALON@0.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.checkBox8.setIcon(icon25)
        self.checkBox8.setIconSize(QtCore.QSize(90, 90))
        self.checkBox8.setCheckable(True)
        self.checkBox8.setObjectName("checkBox8")
        self.gridLayout_2.addWidget(self.checkBox8, 10, 0, 1, 1)
        self.checkBox2 = QtWidgets.QCheckBox(self.Into_Frame_Item_1)
        self.checkBox2.setText("")
        icon26 = QtGui.QIcon()
        icon26.addPixmap(QtGui.QPixmap("Pictures/T6_HEAD_CLOTH_SET3@0.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.checkBox2.setIcon(icon26)
        self.checkBox2.setIconSize(QtCore.QSize(90, 90))
        self.checkBox2.setCheckable(True)
        self.checkBox2.setObjectName("checkBox2")
        self.gridLayout_2.addWidget(self.checkBox2, 4, 0, 1, 1)
        self.Main_Frame_Item.addTab(self.Clotch, "")
        self.Kozaa = QtWidgets.QWidget()
        self.Kozaa.setObjectName("Kozaa")
        self.Into_Frame_Item_2 = QtWidgets.QFrame(self.Kozaa)
        self.Into_Frame_Item_2.setGeometry(QtCore.QRect(5, 5, 460, 860))
        self.Into_Frame_Item_2.setObjectName("Into_Frame_Item_2")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.Into_Frame_Item_2)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.checkBox28 = QtWidgets.QCheckBox(self.Into_Frame_Item_2)
        self.checkBox28.setText("")
        icon27 = QtGui.QIcon()
        icon27.addPixmap(QtGui.QPixmap("Pictures/T6_HEAD_LEATHER_SET1@0.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.checkBox28.setIcon(icon27)
        self.checkBox28.setIconSize(QtCore.QSize(90, 90))
        self.checkBox28.setCheckable(True)
        self.checkBox28.setObjectName("checkBox28")
        self.gridLayout_3.addWidget(self.checkBox28, 2, 0, 1, 1)
        self.checkBox37 = QtWidgets.QCheckBox(self.Into_Frame_Item_2)
        self.checkBox37.setText("")
        icon28 = QtGui.QIcon()
        icon28.addPixmap(QtGui.QPixmap("Pictures/T6_ARMOR_LEATHER_SET1@0.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.checkBox37.setIcon(icon28)
        self.checkBox37.setIconSize(QtCore.QSize(90, 90))
        self.checkBox37.setCheckable(True)
        self.checkBox37.setObjectName("checkBox37")
        self.gridLayout_3.addWidget(self.checkBox37, 2, 1, 1, 1)
        self.checkBox29 = QtWidgets.QCheckBox(self.Into_Frame_Item_2)
        self.checkBox29.setText("")
        icon29 = QtGui.QIcon()
        icon29.addPixmap(QtGui.QPixmap("Pictures/T6_HEAD_LEATHER_SET2@0.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.checkBox29.setIcon(icon29)
        self.checkBox29.setIconSize(QtCore.QSize(90, 90))
        self.checkBox29.setCheckable(True)
        self.checkBox29.setObjectName("checkBox29")
        self.gridLayout_3.addWidget(self.checkBox29, 3, 0, 1, 1)
        self.checkBox46 = QtWidgets.QCheckBox(self.Into_Frame_Item_2)
        self.checkBox46.setText("")
        icon30 = QtGui.QIcon()
        icon30.addPixmap(QtGui.QPixmap("Pictures/T6_SHOES_LEATHER_SET1@0.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.checkBox46.setIcon(icon30)
        self.checkBox46.setIconSize(QtCore.QSize(90, 90))
        self.checkBox46.setCheckable(True)
        self.checkBox46.setObjectName("checkBox46")
        self.gridLayout_3.addWidget(self.checkBox46, 2, 2, 1, 1)
        self.checkBox53 = QtWidgets.QCheckBox(self.Into_Frame_Item_2)
        self.checkBox53.setText("")
        icon31 = QtGui.QIcon()
        icon31.addPixmap(QtGui.QPixmap("Pictures/T6_SHOES_LEATHER_AVALON@0.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.checkBox53.setIcon(icon31)
        self.checkBox53.setIconSize(QtCore.QSize(90, 90))
        self.checkBox53.setCheckable(True)
        self.checkBox53.setObjectName("checkBox53")
        self.gridLayout_3.addWidget(self.checkBox53, 9, 2, 1, 1)
        self.checkBox41 = QtWidgets.QCheckBox(self.Into_Frame_Item_2)
        self.checkBox41.setText("")
        icon32 = QtGui.QIcon()
        icon32.addPixmap(QtGui.QPixmap("Pictures/T6_ARMOR_LEATHER_ROYAL@0.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.checkBox41.setIcon(icon32)
        self.checkBox41.setIconSize(QtCore.QSize(90, 90))
        self.checkBox41.setCheckable(True)
        self.checkBox41.setObjectName("checkBox41")
        self.gridLayout_3.addWidget(self.checkBox41, 6, 1, 1, 1)
        self.checkBox39 = QtWidgets.QCheckBox(self.Into_Frame_Item_2)
        self.checkBox39.setText("")
        icon33 = QtGui.QIcon()
        icon33.addPixmap(QtGui.QPixmap("Pictures/T6_ARMOR_LEATHER_SET3@0.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.checkBox39.setIcon(icon33)
        self.checkBox39.setIconSize(QtCore.QSize(90, 90))
        self.checkBox39.setCheckable(True)
        self.checkBox39.setObjectName("checkBox39")
        self.gridLayout_3.addWidget(self.checkBox39, 4, 1, 1, 1)
        self.checkBox40 = QtWidgets.QCheckBox(self.Into_Frame_Item_2)
        self.checkBox40.setText("")
        icon34 = QtGui.QIcon()
        icon34.addPixmap(QtGui.QPixmap("Pictures/T6_ARMOR_LEATHER_MORGANA@0.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.checkBox40.setIcon(icon34)
        self.checkBox40.setIconSize(QtCore.QSize(90, 90))
        self.checkBox40.setCheckable(True)
        self.checkBox40.setObjectName("checkBox40")
        self.gridLayout_3.addWidget(self.checkBox40, 5, 1, 1, 1)
        self.checkBox38 = QtWidgets.QCheckBox(self.Into_Frame_Item_2)
        self.checkBox38.setText("")
        icon35 = QtGui.QIcon()
        icon35.addPixmap(QtGui.QPixmap("Pictures/T6_ARMOR_LEATHER_SET2@0.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.checkBox38.setIcon(icon35)
        self.checkBox38.setIconSize(QtCore.QSize(90, 90))
        self.checkBox38.setCheckable(True)
        self.checkBox38.setObjectName("checkBox38")
        self.gridLayout_3.addWidget(self.checkBox38, 3, 1, 1, 1)
        self.checkBox36 = QtWidgets.QCheckBox(self.Into_Frame_Item_2)
        self.checkBox36.setText("")
        icon36 = QtGui.QIcon()
        icon36.addPixmap(QtGui.QPixmap("Pictures/T6_HEAD_LEATHER_FEY@0.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.checkBox36.setIcon(icon36)
        self.checkBox36.setIconSize(QtCore.QSize(90, 90))
        self.checkBox36.setCheckable(True)
        self.checkBox36.setObjectName("checkBox36")
        self.gridLayout_3.addWidget(self.checkBox36, 10, 0, 1, 1)
        self.checkBox45 = QtWidgets.QCheckBox(self.Into_Frame_Item_2)
        self.checkBox45.setText("")
        icon37 = QtGui.QIcon()
        icon37.addPixmap(QtGui.QPixmap("Pictures/T6_ARMOR_LEATHER_FEY@0.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.checkBox45.setIcon(icon37)
        self.checkBox45.setIconSize(QtCore.QSize(90, 90))
        self.checkBox45.setCheckable(True)
        self.checkBox45.setObjectName("checkBox45")
        self.gridLayout_3.addWidget(self.checkBox45, 10, 1, 1, 1)
        self.checkBox47 = QtWidgets.QCheckBox(self.Into_Frame_Item_2)
        self.checkBox47.setText("")
        icon38 = QtGui.QIcon()
        icon38.addPixmap(QtGui.QPixmap("Pictures/T6_SHOES_LEATHER_SET2@0.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.checkBox47.setIcon(icon38)
        self.checkBox47.setIconSize(QtCore.QSize(90, 90))
        self.checkBox47.setCheckable(True)
        self.checkBox47.setObjectName("checkBox47")
        self.gridLayout_3.addWidget(self.checkBox47, 3, 2, 1, 1)
        self.checkBox43 = QtWidgets.QCheckBox(self.Into_Frame_Item_2)
        self.checkBox43.setText("")
        icon39 = QtGui.QIcon()
        icon39.addPixmap(QtGui.QPixmap("Pictures/T6_ARMOR_LEATHER_UNDEAD@0.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.checkBox43.setIcon(icon39)
        self.checkBox43.setIconSize(QtCore.QSize(90, 90))
        self.checkBox43.setCheckable(True)
        self.checkBox43.setObjectName("checkBox43")
        self.gridLayout_3.addWidget(self.checkBox43, 8, 1, 1, 1)
        self.checkBox44 = QtWidgets.QCheckBox(self.Into_Frame_Item_2)
        self.checkBox44.setText("")
        icon40 = QtGui.QIcon()
        icon40.addPixmap(QtGui.QPixmap("Pictures/T6_ARMOR_LEATHER_AVALON@0.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.checkBox44.setIcon(icon40)
        self.checkBox44.setIconSize(QtCore.QSize(90, 90))
        self.checkBox44.setCheckable(True)
        self.checkBox44.setObjectName("checkBox44")
        self.gridLayout_3.addWidget(self.checkBox44, 9, 1, 1, 1)
        self.checkBox42 = QtWidgets.QCheckBox(self.Into_Frame_Item_2)
        self.checkBox42.setText("")
        icon41 = QtGui.QIcon()
        icon41.addPixmap(QtGui.QPixmap("Pictures/T6_ARMOR_LEATHER_HELL@0.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.checkBox42.setIcon(icon41)
        self.checkBox42.setIconSize(QtCore.QSize(90, 90))
        self.checkBox42.setCheckable(True)
        self.checkBox42.setObjectName("checkBox42")
        self.gridLayout_3.addWidget(self.checkBox42, 7, 1, 1, 1)
        self.checkBox33 = QtWidgets.QCheckBox(self.Into_Frame_Item_2)
        self.checkBox33.setText("")
        icon42 = QtGui.QIcon()
        icon42.addPixmap(QtGui.QPixmap("Pictures/T6_HEAD_LEATHER_HELL@0.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.checkBox33.setIcon(icon42)
        self.checkBox33.setIconSize(QtCore.QSize(90, 90))
        self.checkBox33.setCheckable(True)
        self.checkBox33.setObjectName("checkBox33")
        self.gridLayout_3.addWidget(self.checkBox33, 7, 0, 1, 1)
        self.checkBox34 = QtWidgets.QCheckBox(self.Into_Frame_Item_2)
        self.checkBox34.setText("")
        icon43 = QtGui.QIcon()
        icon43.addPixmap(QtGui.QPixmap("Pictures/T6_HEAD_LEATHER_UNDEAD@0.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.checkBox34.setIcon(icon43)
        self.checkBox34.setIconSize(QtCore.QSize(90, 90))
        self.checkBox34.setCheckable(True)
        self.checkBox34.setObjectName("checkBox34")
        self.gridLayout_3.addWidget(self.checkBox34, 8, 0, 1, 1)
        self.checkBox31 = QtWidgets.QCheckBox(self.Into_Frame_Item_2)
        self.checkBox31.setText("")
        icon44 = QtGui.QIcon()
        icon44.addPixmap(QtGui.QPixmap("Pictures/T6_HEAD_LEATHER_MORGANA@0.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.checkBox31.setIcon(icon44)
        self.checkBox31.setIconSize(QtCore.QSize(90, 90))
        self.checkBox31.setCheckable(True)
        self.checkBox31.setObjectName("checkBox31")
        self.gridLayout_3.addWidget(self.checkBox31, 5, 0, 1, 1)
        self.checkBox30 = QtWidgets.QCheckBox(self.Into_Frame_Item_2)
        self.checkBox30.setText("")
        icon45 = QtGui.QIcon()
        icon45.addPixmap(QtGui.QPixmap("Pictures/T6_HEAD_LEATHER_SET3@0.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.checkBox30.setIcon(icon45)
        self.checkBox30.setIconSize(QtCore.QSize(90, 90))
        self.checkBox30.setCheckable(True)
        self.checkBox30.setObjectName("checkBox30")
        self.gridLayout_3.addWidget(self.checkBox30, 4, 0, 1, 1)
        self.checkBox32 = QtWidgets.QCheckBox(self.Into_Frame_Item_2)
        self.checkBox32.setText("")
        icon46 = QtGui.QIcon()
        icon46.addPixmap(QtGui.QPixmap("Pictures/T6_HEAD_LEATHER_ROYAL@0.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.checkBox32.setIcon(icon46)
        self.checkBox32.setIconSize(QtCore.QSize(90, 90))
        self.checkBox32.setCheckable(True)
        self.checkBox32.setObjectName("checkBox32")
        self.gridLayout_3.addWidget(self.checkBox32, 6, 0, 1, 1)
        self.checkBox35 = QtWidgets.QCheckBox(self.Into_Frame_Item_2)
        self.checkBox35.setText("")
        icon47 = QtGui.QIcon()
        icon47.addPixmap(QtGui.QPixmap("Pictures/T6_HEAD_LEATHER_AVALON@0.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.checkBox35.setIcon(icon47)
        self.checkBox35.setIconSize(QtCore.QSize(90, 90))
        self.checkBox35.setCheckable(True)
        self.checkBox35.setObjectName("checkBox35")
        self.gridLayout_3.addWidget(self.checkBox35, 9, 0, 1, 1)
        self.checkBox54 = QtWidgets.QCheckBox(self.Into_Frame_Item_2)
        self.checkBox54.setText("")
        icon48 = QtGui.QIcon()
        icon48.addPixmap(QtGui.QPixmap("Pictures/T6_SHOES_LEATHER_FEY@0.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.checkBox54.setIcon(icon48)
        self.checkBox54.setIconSize(QtCore.QSize(90, 90))
        self.checkBox54.setCheckable(True)
        self.checkBox54.setObjectName("checkBox54")
        self.gridLayout_3.addWidget(self.checkBox54, 10, 2, 1, 1)
        self.checkBox51 = QtWidgets.QCheckBox(self.Into_Frame_Item_2)
        self.checkBox51.setText("")
        icon49 = QtGui.QIcon()
        icon49.addPixmap(QtGui.QPixmap("Pictures/T6_SHOES_LEATHER_HELL@0.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.checkBox51.setIcon(icon49)
        self.checkBox51.setIconSize(QtCore.QSize(90, 90))
        self.checkBox51.setCheckable(True)
        self.checkBox51.setObjectName("checkBox51")
        self.gridLayout_3.addWidget(self.checkBox51, 7, 2, 1, 1)
        self.checkBox50 = QtWidgets.QCheckBox(self.Into_Frame_Item_2)
        self.checkBox50.setText("")
        icon50 = QtGui.QIcon()
        icon50.addPixmap(QtGui.QPixmap("Pictures/T6_SHOES_LEATHER_ROYAL@0.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.checkBox50.setIcon(icon50)
        self.checkBox50.setIconSize(QtCore.QSize(90, 90))
        self.checkBox50.setCheckable(True)
        self.checkBox50.setObjectName("checkBox50")
        self.gridLayout_3.addWidget(self.checkBox50, 6, 2, 1, 1)
        self.checkBox49 = QtWidgets.QCheckBox(self.Into_Frame_Item_2)
        self.checkBox49.setText("")
        icon51 = QtGui.QIcon()
        icon51.addPixmap(QtGui.QPixmap("Pictures/T6_SHOES_LEATHER_MORGANA@0.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.checkBox49.setIcon(icon51)
        self.checkBox49.setIconSize(QtCore.QSize(90, 90))
        self.checkBox49.setCheckable(True)
        self.checkBox49.setObjectName("checkBox49")
        self.gridLayout_3.addWidget(self.checkBox49, 5, 2, 1, 1)
        self.checkBox48 = QtWidgets.QCheckBox(self.Into_Frame_Item_2)
        self.checkBox48.setText("")
        icon52 = QtGui.QIcon()
        icon52.addPixmap(QtGui.QPixmap("Pictures/T6_SHOES_LEATHER_SET3@0.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.checkBox48.setIcon(icon52)
        self.checkBox48.setIconSize(QtCore.QSize(90, 90))
        self.checkBox48.setCheckable(True)
        self.checkBox48.setObjectName("checkBox48")
        self.gridLayout_3.addWidget(self.checkBox48, 4, 2, 1, 1)
        self.checkBox52 = QtWidgets.QCheckBox(self.Into_Frame_Item_2)
        self.checkBox52.setText("")
        icon53 = QtGui.QIcon()
        icon53.addPixmap(QtGui.QPixmap("Pictures/T6_SHOES_LEATHER_UNDEAD@0.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.checkBox52.setIcon(icon53)
        self.checkBox52.setIconSize(QtCore.QSize(90, 90))
        self.checkBox52.setCheckable(True)
        self.checkBox52.setObjectName("checkBox52")
        self.gridLayout_3.addWidget(self.checkBox52, 8, 2, 1, 1)
        self.Main_Frame_Item.addTab(self.Kozaa, "")
        self.Lat = QtWidgets.QWidget()
        self.Lat.setObjectName("Lat")
        self.Into_Frame_Item_3 = QtWidgets.QFrame(self.Lat)
        self.Into_Frame_Item_3.setGeometry(QtCore.QRect(5, 5, 460, 860))
        self.Into_Frame_Item_3.setObjectName("Into_Frame_Item_3")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.Into_Frame_Item_3)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.checkBox79 = QtWidgets.QCheckBox(self.Into_Frame_Item_3)
        self.checkBox79.setText("")
        icon54 = QtGui.QIcon()
        icon54.addPixmap(QtGui.QPixmap("Pictures/T6_SHOES_PLATE_KEEPER@0.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.checkBox79.setIcon(icon54)
        self.checkBox79.setIconSize(QtCore.QSize(90, 90))
        self.checkBox79.setCheckable(True)
        self.checkBox79.setObjectName("checkBox79")
        self.gridLayout_4.addWidget(self.checkBox79, 8, 2, 1, 1)
        self.checkBox75 = QtWidgets.QCheckBox(self.Into_Frame_Item_3)
        self.checkBox75.setText("")
        icon55 = QtGui.QIcon()
        icon55.addPixmap(QtGui.QPixmap("Pictures/T6_SHOES_PLATE_SET3@0.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.checkBox75.setIcon(icon55)
        self.checkBox75.setIconSize(QtCore.QSize(90, 90))
        self.checkBox75.setCheckable(True)
        self.checkBox75.setObjectName("checkBox75")
        self.gridLayout_4.addWidget(self.checkBox75, 4, 2, 1, 1)
        self.checkBox76 = QtWidgets.QCheckBox(self.Into_Frame_Item_3)
        self.checkBox76.setText("")
        icon56 = QtGui.QIcon()
        icon56.addPixmap(QtGui.QPixmap("Pictures/T6_SHOES_PLATE_UNDEAD@0.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.checkBox76.setIcon(icon56)
        self.checkBox76.setIconSize(QtCore.QSize(90, 90))
        self.checkBox76.setCheckable(True)
        self.checkBox76.setObjectName("checkBox76")
        self.gridLayout_4.addWidget(self.checkBox76, 5, 2, 1, 1)
        self.checkBox78 = QtWidgets.QCheckBox(self.Into_Frame_Item_3)
        self.checkBox78.setText("")
        icon57 = QtGui.QIcon()
        icon57.addPixmap(QtGui.QPixmap("Pictures/T6_SHOES_PLATE_HELL@0.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.checkBox78.setIcon(icon57)
        self.checkBox78.setIconSize(QtCore.QSize(90, 90))
        self.checkBox78.setCheckable(True)
        self.checkBox78.setObjectName("checkBox78")
        self.gridLayout_4.addWidget(self.checkBox78, 7, 2, 1, 1)
        self.checkBox77 = QtWidgets.QCheckBox(self.Into_Frame_Item_3)
        self.checkBox77.setText("")
        icon58 = QtGui.QIcon()
        icon58.addPixmap(QtGui.QPixmap("Pictures/T6_SHOES_PLATE_ROYAL@0.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.checkBox77.setIcon(icon58)
        self.checkBox77.setIconSize(QtCore.QSize(90, 90))
        self.checkBox77.setCheckable(True)
        self.checkBox77.setObjectName("checkBox77")
        self.gridLayout_4.addWidget(self.checkBox77, 6, 2, 1, 1)
        self.checkBox64 = QtWidgets.QCheckBox(self.Into_Frame_Item_3)
        self.checkBox64.setText("")
        icon59 = QtGui.QIcon()
        icon59.addPixmap(QtGui.QPixmap("Pictures/T6_ARMOR_PLATE_SET1@0.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.checkBox64.setIcon(icon59)
        self.checkBox64.setIconSize(QtCore.QSize(90, 90))
        self.checkBox64.setCheckable(True)
        self.checkBox64.setObjectName("checkBox64")
        self.gridLayout_4.addWidget(self.checkBox64, 2, 1, 1, 1)
        self.checkBox55 = QtWidgets.QCheckBox(self.Into_Frame_Item_3)
        self.checkBox55.setText("")
        icon60 = QtGui.QIcon()
        icon60.addPixmap(QtGui.QPixmap("Pictures/T6_HEAD_PLATE_SET1@0.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.checkBox55.setIcon(icon60)
        self.checkBox55.setIconSize(QtCore.QSize(90, 90))
        self.checkBox55.setCheckable(True)
        self.checkBox55.setObjectName("checkBox55")
        self.gridLayout_4.addWidget(self.checkBox55, 2, 0, 1, 1)
        self.checkBox73 = QtWidgets.QCheckBox(self.Into_Frame_Item_3)
        self.checkBox73.setText("")
        icon61 = QtGui.QIcon()
        icon61.addPixmap(QtGui.QPixmap("Pictures/T6_SHOES_PLATE_SET1@0.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.checkBox73.setIcon(icon61)
        self.checkBox73.setIconSize(QtCore.QSize(90, 90))
        self.checkBox73.setCheckable(True)
        self.checkBox73.setObjectName("checkBox73")
        self.gridLayout_4.addWidget(self.checkBox73, 2, 2, 1, 1)
        self.checkBox56 = QtWidgets.QCheckBox(self.Into_Frame_Item_3)
        self.checkBox56.setText("")
        icon62 = QtGui.QIcon()
        icon62.addPixmap(QtGui.QPixmap("Pictures/T6_HEAD_PLATE_SET2@0.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.checkBox56.setIcon(icon62)
        self.checkBox56.setIconSize(QtCore.QSize(90, 90))
        self.checkBox56.setCheckable(True)
        self.checkBox56.setObjectName("checkBox56")
        self.gridLayout_4.addWidget(self.checkBox56, 3, 0, 1, 1)
        self.checkBox57 = QtWidgets.QCheckBox(self.Into_Frame_Item_3)
        self.checkBox57.setText("")
        icon63 = QtGui.QIcon()
        icon63.addPixmap(QtGui.QPixmap("Pictures/T6_HEAD_PLATE_SET3@0.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.checkBox57.setIcon(icon63)
        self.checkBox57.setIconSize(QtCore.QSize(90, 90))
        self.checkBox57.setCheckable(True)
        self.checkBox57.setObjectName("checkBox57")
        self.gridLayout_4.addWidget(self.checkBox57, 4, 0, 1, 1)
        self.checkBox67 = QtWidgets.QCheckBox(self.Into_Frame_Item_3)
        self.checkBox67.setText("")
        icon64 = QtGui.QIcon()
        icon64.addPixmap(QtGui.QPixmap("Pictures/T6_ARMOR_PLATE_UNDEAD@0.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.checkBox67.setIcon(icon64)
        self.checkBox67.setIconSize(QtCore.QSize(90, 90))
        self.checkBox67.setCheckable(True)
        self.checkBox67.setObjectName("checkBox67")
        self.gridLayout_4.addWidget(self.checkBox67, 5, 1, 1, 1)
        self.checkBox68 = QtWidgets.QCheckBox(self.Into_Frame_Item_3)
        self.checkBox68.setText("")
        icon65 = QtGui.QIcon()
        icon65.addPixmap(QtGui.QPixmap("Pictures/T6_ARMOR_PLATE_ROYAL@0.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.checkBox68.setIcon(icon65)
        self.checkBox68.setIconSize(QtCore.QSize(90, 90))
        self.checkBox68.setCheckable(True)
        self.checkBox68.setObjectName("checkBox68")
        self.gridLayout_4.addWidget(self.checkBox68, 6, 1, 1, 1)
        self.checkBox70 = QtWidgets.QCheckBox(self.Into_Frame_Item_3)
        self.checkBox70.setText("")
        icon66 = QtGui.QIcon()
        icon66.addPixmap(QtGui.QPixmap("Pictures/T6_ARMOR_PLATE_KEEPER@0.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.checkBox70.setIcon(icon66)
        self.checkBox70.setIconSize(QtCore.QSize(90, 90))
        self.checkBox70.setCheckable(True)
        self.checkBox70.setObjectName("checkBox70")
        self.gridLayout_4.addWidget(self.checkBox70, 8, 1, 1, 1)
        self.checkBox66 = QtWidgets.QCheckBox(self.Into_Frame_Item_3)
        self.checkBox66.setText("")
        icon67 = QtGui.QIcon()
        icon67.addPixmap(QtGui.QPixmap("Pictures/T6_ARMOR_PLATE_SET3@0.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.checkBox66.setIcon(icon67)
        self.checkBox66.setIconSize(QtCore.QSize(90, 90))
        self.checkBox66.setCheckable(True)
        self.checkBox66.setObjectName("checkBox66")
        self.gridLayout_4.addWidget(self.checkBox66, 4, 1, 1, 1)
        self.checkBox65 = QtWidgets.QCheckBox(self.Into_Frame_Item_3)
        self.checkBox65.setText("")
        icon68 = QtGui.QIcon()
        icon68.addPixmap(QtGui.QPixmap("Pictures/T6_ARMOR_PLATE_SET2@0.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.checkBox65.setIcon(icon68)
        self.checkBox65.setIconSize(QtCore.QSize(90, 90))
        self.checkBox65.setCheckable(True)
        self.checkBox65.setObjectName("checkBox65")
        self.gridLayout_4.addWidget(self.checkBox65, 3, 1, 1, 1)
        self.checkBox69 = QtWidgets.QCheckBox(self.Into_Frame_Item_3)
        self.checkBox69.setText("")
        icon69 = QtGui.QIcon()
        icon69.addPixmap(QtGui.QPixmap("Pictures/T6_ARMOR_PLATE_HELL@0.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.checkBox69.setIcon(icon69)
        self.checkBox69.setIconSize(QtCore.QSize(90, 90))
        self.checkBox69.setCheckable(True)
        self.checkBox69.setObjectName("checkBox69")
        self.gridLayout_4.addWidget(self.checkBox69, 7, 1, 1, 1)
        self.checkBox81 = QtWidgets.QCheckBox(self.Into_Frame_Item_3)
        self.checkBox81.setText("")
        icon70 = QtGui.QIcon()
        icon70.addPixmap(QtGui.QPixmap("Pictures/T6_SHOES_PLATE_FEY@0.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.checkBox81.setIcon(icon70)
        self.checkBox81.setIconSize(QtCore.QSize(90, 90))
        self.checkBox81.setCheckable(True)
        self.checkBox81.setObjectName("checkBox81")
        self.gridLayout_4.addWidget(self.checkBox81, 10, 2, 1, 1)
        self.checkBox71 = QtWidgets.QCheckBox(self.Into_Frame_Item_3)
        self.checkBox71.setText("")
        icon71 = QtGui.QIcon()
        icon71.addPixmap(QtGui.QPixmap("Pictures/T6_ARMOR_PLATE_AVALON@0.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.checkBox71.setIcon(icon71)
        self.checkBox71.setIconSize(QtCore.QSize(90, 90))
        self.checkBox71.setCheckable(True)
        self.checkBox71.setObjectName("checkBox71")
        self.gridLayout_4.addWidget(self.checkBox71, 9, 1, 1, 1)
        self.checkBox72 = QtWidgets.QCheckBox(self.Into_Frame_Item_3)
        self.checkBox72.setText("")
        icon72 = QtGui.QIcon()
        icon72.addPixmap(QtGui.QPixmap("Pictures/T6_ARMOR_PLATE_FEY@0.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.checkBox72.setIcon(icon72)
        self.checkBox72.setIconSize(QtCore.QSize(90, 90))
        self.checkBox72.setCheckable(True)
        self.checkBox72.setObjectName("checkBox72")
        self.gridLayout_4.addWidget(self.checkBox72, 10, 1, 1, 1)
        self.checkBox80 = QtWidgets.QCheckBox(self.Into_Frame_Item_3)
        self.checkBox80.setText("")
        icon73 = QtGui.QIcon()
        icon73.addPixmap(QtGui.QPixmap("Pictures/T6_SHOES_PLATE_AVALON@0.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.checkBox80.setIcon(icon73)
        self.checkBox80.setIconSize(QtCore.QSize(90, 90))
        self.checkBox80.setCheckable(True)
        self.checkBox80.setObjectName("checkBox80")
        self.gridLayout_4.addWidget(self.checkBox80, 9, 2, 1, 1)
        self.checkBox74 = QtWidgets.QCheckBox(self.Into_Frame_Item_3)
        self.checkBox74.setText("")
        icon74 = QtGui.QIcon()
        icon74.addPixmap(QtGui.QPixmap("Pictures/T6_SHOES_PLATE_SET2@0.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.checkBox74.setIcon(icon74)
        self.checkBox74.setIconSize(QtCore.QSize(90, 90))
        self.checkBox74.setCheckable(True)
        self.checkBox74.setObjectName("checkBox74")
        self.gridLayout_4.addWidget(self.checkBox74, 3, 2, 1, 1)
        self.checkBox62 = QtWidgets.QCheckBox(self.Into_Frame_Item_3)
        self.checkBox62.setText("")
        icon75 = QtGui.QIcon()
        icon75.addPixmap(QtGui.QPixmap("Pictures/T6_HEAD_PLATE_AVALON@0.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.checkBox62.setIcon(icon75)
        self.checkBox62.setIconSize(QtCore.QSize(90, 90))
        self.checkBox62.setCheckable(True)
        self.checkBox62.setObjectName("checkBox62")
        self.gridLayout_4.addWidget(self.checkBox62, 9, 0, 1, 1)
        self.checkBox61 = QtWidgets.QCheckBox(self.Into_Frame_Item_3)
        self.checkBox61.setText("")
        icon76 = QtGui.QIcon()
        icon76.addPixmap(QtGui.QPixmap("Pictures/T6_HEAD_PLATE_KEEPER@0.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.checkBox61.setIcon(icon76)
        self.checkBox61.setIconSize(QtCore.QSize(90, 90))
        self.checkBox61.setCheckable(True)
        self.checkBox61.setObjectName("checkBox61")
        self.gridLayout_4.addWidget(self.checkBox61, 8, 0, 1, 1)
        self.checkBox58 = QtWidgets.QCheckBox(self.Into_Frame_Item_3)
        self.checkBox58.setText("")
        icon77 = QtGui.QIcon()
        icon77.addPixmap(QtGui.QPixmap("Pictures/T6_HEAD_PLATE_UNDEAD@0.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.checkBox58.setIcon(icon77)
        self.checkBox58.setIconSize(QtCore.QSize(90, 90))
        self.checkBox58.setCheckable(True)
        self.checkBox58.setObjectName("checkBox58")
        self.gridLayout_4.addWidget(self.checkBox58, 5, 0, 1, 1)
        self.checkBox59 = QtWidgets.QCheckBox(self.Into_Frame_Item_3)
        self.checkBox59.setText("")
        icon78 = QtGui.QIcon()
        icon78.addPixmap(QtGui.QPixmap("Pictures/T6_HEAD_PLATE_ROYAL@0.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.checkBox59.setIcon(icon78)
        self.checkBox59.setIconSize(QtCore.QSize(90, 90))
        self.checkBox59.setCheckable(True)
        self.checkBox59.setObjectName("checkBox59")
        self.gridLayout_4.addWidget(self.checkBox59, 6, 0, 1, 1)
        self.checkBox60 = QtWidgets.QCheckBox(self.Into_Frame_Item_3)
        self.checkBox60.setText("")
        icon79 = QtGui.QIcon()
        icon79.addPixmap(QtGui.QPixmap("Pictures/T6_HEAD_PLATE_HELL@0.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.checkBox60.setIcon(icon79)
        self.checkBox60.setIconSize(QtCore.QSize(90, 90))
        self.checkBox60.setCheckable(True)
        self.checkBox60.setObjectName("checkBox60")
        self.gridLayout_4.addWidget(self.checkBox60, 7, 0, 1, 1)
        self.checkBox63 = QtWidgets.QCheckBox(self.Into_Frame_Item_3)
        self.checkBox63.setText("")
        icon80 = QtGui.QIcon()
        icon80.addPixmap(QtGui.QPixmap("Pictures/T6_HEAD_PLATE_FEY@0.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.checkBox63.setIcon(icon80)
        self.checkBox63.setIconSize(QtCore.QSize(90, 90))
        self.checkBox63.setCheckable(True)
        self.checkBox63.setObjectName("checkBox63")
        self.gridLayout_4.addWidget(self.checkBox63, 10, 0, 1, 1)
        self.Main_Frame_Item.addTab(self.Lat, "")
        self.Bags = QtWidgets.QWidget()
        self.Bags.setObjectName("Bags")
        self.Into_Frame_Item_5 = QtWidgets.QFrame(self.Bags)
        self.Into_Frame_Item_5.setGeometry(QtCore.QRect(5, 5, 460, 860))
        self.Into_Frame_Item_5.setObjectName("Into_Frame_Item_5")
        self.gridLayout_7 = QtWidgets.QGridLayout(self.Into_Frame_Item_5)
        self.gridLayout_7.setObjectName("gridLayout_7")
        self.checkBox22_2 = QtWidgets.QCheckBox(self.Into_Frame_Item_5)
        font = QtGui.QFont()
        font.setPointSize(8)
        self.checkBox22_2.setFont(font)
        self.checkBox22_2.setText("")
        icon81 = QtGui.QIcon()
        icon81.addPixmap(QtGui.QPixmap("Pictures/Master\'s Morgana Cape.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.checkBox22_2.setIcon(icon81)
        self.checkBox22_2.setIconSize(QtCore.QSize(95, 95))
        self.checkBox22_2.setCheckable(True)
        self.checkBox22_2.setObjectName("checkBox22_2")
        self.gridLayout_7.addWidget(self.checkBox22_2, 3, 2, 1, 1)
        self.checkBox19_2 = QtWidgets.QCheckBox(self.Into_Frame_Item_5)
        font = QtGui.QFont()
        font.setPointSize(8)
        self.checkBox19_2.setFont(font)
        self.checkBox19_2.setText("")
        icon82 = QtGui.QIcon()
        icon82.addPixmap(QtGui.QPixmap("Pictures/Master\'s Demon Cape.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.checkBox19_2.setIcon(icon82)
        self.checkBox19_2.setIconSize(QtCore.QSize(95, 95))
        self.checkBox19_2.setCheckable(True)
        self.checkBox19_2.setObjectName("checkBox19_2")
        self.gridLayout_7.addWidget(self.checkBox19_2, 4, 0, 1, 1)
        self.checkBox23_2 = QtWidgets.QCheckBox(self.Into_Frame_Item_5)
        font = QtGui.QFont()
        font.setPointSize(8)
        self.checkBox23_2.setFont(font)
        self.checkBox23_2.setText("")
        icon83 = QtGui.QIcon()
        icon83.addPixmap(QtGui.QPixmap("Pictures/Master\'s Undead Cape.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.checkBox23_2.setIcon(icon83)
        self.checkBox23_2.setIconSize(QtCore.QSize(95, 95))
        self.checkBox23_2.setCheckable(True)
        self.checkBox23_2.setObjectName("checkBox23_2")
        self.gridLayout_7.addWidget(self.checkBox23_2, 4, 1, 1, 1)
        self.checkBox21_2 = QtWidgets.QCheckBox(self.Into_Frame_Item_5)
        font = QtGui.QFont()
        font.setPointSize(8)
        self.checkBox21_2.setFont(font)
        self.checkBox21_2.setText("")
        icon84 = QtGui.QIcon()
        icon84.addPixmap(QtGui.QPixmap("Pictures/Master\'s Keeper Cape.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.checkBox21_2.setIcon(icon84)
        self.checkBox21_2.setIconSize(QtCore.QSize(95, 95))
        self.checkBox21_2.setCheckable(True)
        self.checkBox21_2.setObjectName("checkBox21_2")
        self.gridLayout_7.addWidget(self.checkBox21_2, 3, 1, 1, 1)
        self.checkBox24_2 = QtWidgets.QCheckBox(self.Into_Frame_Item_5)
        font = QtGui.QFont()
        font.setPointSize(8)
        self.checkBox24_2.setFont(font)
        self.checkBox24_2.setText("")
        icon85 = QtGui.QIcon()
        icon85.addPixmap(QtGui.QPixmap("Pictures/Master\'s Caerleon Cape.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.checkBox24_2.setIcon(icon85)
        self.checkBox24_2.setIconSize(QtCore.QSize(95, 95))
        self.checkBox24_2.setCheckable(True)
        self.checkBox24_2.setObjectName("checkBox24_2")
        self.gridLayout_7.addWidget(self.checkBox24_2, 4, 2, 1, 1)
        self.checkBox20_2 = QtWidgets.QCheckBox(self.Into_Frame_Item_5)
        font = QtGui.QFont()
        font.setPointSize(8)
        self.checkBox20_2.setFont(font)
        self.checkBox20_2.setText("")
        icon86 = QtGui.QIcon()
        icon86.addPixmap(QtGui.QPixmap("Pictures/Master\'s Heretic Cape.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.checkBox20_2.setIcon(icon86)
        self.checkBox20_2.setIconSize(QtCore.QSize(95, 95))
        self.checkBox20_2.setCheckable(True)
        self.checkBox20_2.setObjectName("checkBox20_2")
        self.gridLayout_7.addWidget(self.checkBox20_2, 3, 0, 1, 1)
        self.checkBox11_2 = QtWidgets.QCheckBox(self.Into_Frame_Item_5)
        font = QtGui.QFont()
        font.setPointSize(8)
        self.checkBox11_2.setFont(font)
        self.checkBox11_2.setText("")
        icon87 = QtGui.QIcon()
        icon87.addPixmap(QtGui.QPixmap("Pictures/Master\'s Fort Sterling Cape.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.checkBox11_2.setIcon(icon87)
        self.checkBox11_2.setIconSize(QtCore.QSize(95, 95))
        self.checkBox11_2.setCheckable(True)
        self.checkBox11_2.setObjectName("checkBox11_2")
        self.gridLayout_7.addWidget(self.checkBox11_2, 5, 0, 1, 1)
        self.checkBox2_2 = QtWidgets.QCheckBox(self.Into_Frame_Item_5)
        font = QtGui.QFont()
        font.setPointSize(8)
        self.checkBox2_2.setFont(font)
        self.checkBox2_2.setText("")
        icon88 = QtGui.QIcon()
        icon88.addPixmap(QtGui.QPixmap("Pictures/Master\'s Satchel of Insight@0.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.checkBox2_2.setIcon(icon88)
        self.checkBox2_2.setIconSize(QtCore.QSize(95, 95))
        self.checkBox2_2.setCheckable(True)
        self.checkBox2_2.setObjectName("checkBox2_2")
        self.gridLayout_7.addWidget(self.checkBox2_2, 1, 1, 1, 1)
        self.checkBox13_2 = QtWidgets.QCheckBox(self.Into_Frame_Item_5)
        font = QtGui.QFont()
        font.setPointSize(8)
        self.checkBox13_2.setFont(font)
        self.checkBox13_2.setText("")
        icon89 = QtGui.QIcon()
        icon89.addPixmap(QtGui.QPixmap("Pictures/Master\'s Martlock Cape.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.checkBox13_2.setIcon(icon89)
        self.checkBox13_2.setIconSize(QtCore.QSize(95, 95))
        self.checkBox13_2.setCheckable(True)
        self.checkBox13_2.setObjectName("checkBox13_2")
        self.gridLayout_7.addWidget(self.checkBox13_2, 6, 0, 1, 1)
        self.checkBox3_2 = QtWidgets.QCheckBox(self.Into_Frame_Item_5)
        font = QtGui.QFont()
        font.setPointSize(8)
        self.checkBox3_2.setFont(font)
        self.checkBox3_2.setText("")
        icon90 = QtGui.QIcon()
        icon90.addPixmap(QtGui.QPixmap("Pictures/Master\'s Cape.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.checkBox3_2.setIcon(icon90)
        self.checkBox3_2.setIconSize(QtCore.QSize(95, 95))
        self.checkBox3_2.setCheckable(True)
        self.checkBox3_2.setObjectName("checkBox3_2")
        self.gridLayout_7.addWidget(self.checkBox3_2, 1, 2, 1, 1)
        self.checkBox1_2 = QtWidgets.QCheckBox(self.Into_Frame_Item_5)
        font = QtGui.QFont()
        font.setPointSize(8)
        self.checkBox1_2.setFont(font)
        self.checkBox1_2.setText("")
        icon91 = QtGui.QIcon()
        icon91.addPixmap(QtGui.QPixmap("Pictures/Master\'s Bag.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.checkBox1_2.setIcon(icon91)
        self.checkBox1_2.setIconSize(QtCore.QSize(95, 95))
        self.checkBox1_2.setCheckable(True)
        self.checkBox1_2.setObjectName("checkBox1_2")
        self.gridLayout_7.addWidget(self.checkBox1_2, 1, 0, 1, 1)
        self.checkBox14_2 = QtWidgets.QCheckBox(self.Into_Frame_Item_5)
        font = QtGui.QFont()
        font.setPointSize(8)
        self.checkBox14_2.setFont(font)
        self.checkBox14_2.setText("")
        icon92 = QtGui.QIcon()
        icon92.addPixmap(QtGui.QPixmap("Pictures/Master\'s Thetford Cape.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.checkBox14_2.setIcon(icon92)
        self.checkBox14_2.setIconSize(QtCore.QSize(95, 95))
        self.checkBox14_2.setCheckable(True)
        self.checkBox14_2.setObjectName("checkBox14_2")
        self.gridLayout_7.addWidget(self.checkBox14_2, 6, 2, 1, 1)
        self.checkBox10_2 = QtWidgets.QCheckBox(self.Into_Frame_Item_5)
        font = QtGui.QFont()
        font.setPointSize(8)
        self.checkBox10_2.setFont(font)
        self.checkBox10_2.setText("")
        icon93 = QtGui.QIcon()
        icon93.addPixmap(QtGui.QPixmap("Pictures/Master\'s Bridgewatch Cape.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.checkBox10_2.setIcon(icon93)
        self.checkBox10_2.setIconSize(QtCore.QSize(95, 95))
        self.checkBox10_2.setCheckable(True)
        self.checkBox10_2.setObjectName("checkBox10_2")
        self.gridLayout_7.addWidget(self.checkBox10_2, 5, 2, 1, 1)
        self.checkBox12_2 = QtWidgets.QCheckBox(self.Into_Frame_Item_5)
        font = QtGui.QFont()
        font.setPointSize(8)
        self.checkBox12_2.setFont(font)
        self.checkBox12_2.setText("")
        icon94 = QtGui.QIcon()
        icon94.addPixmap(QtGui.QPixmap("Pictures/Master\'s Lymhurst Cape.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.checkBox12_2.setIcon(icon94)
        self.checkBox12_2.setIconSize(QtCore.QSize(95, 95))
        self.checkBox12_2.setCheckable(True)
        self.checkBox12_2.setObjectName("checkBox12_2")
        self.gridLayout_7.addWidget(self.checkBox12_2, 5, 1, 1, 1)
        self.Main_Frame_Item.addTab(self.Bags, "")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.Into_Frame_Item_6 = QtWidgets.QFrame(self.tab)
        self.Into_Frame_Item_6.setGeometry(QtCore.QRect(0, 0, 460, 860))
        self.Into_Frame_Item_6.setObjectName("Into_Frame_Item_6")
        self.gridLayout_8 = QtWidgets.QGridLayout(self.Into_Frame_Item_6)
        self.gridLayout_8.setObjectName("gridLayout_8")
        self.checkBox22_3 = QtWidgets.QCheckBox(self.Into_Frame_Item_6)
        font = QtGui.QFont()
        font.setPointSize(8)
        self.checkBox22_3.setFont(font)
        self.checkBox22_3.setText("")
        icon95 = QtGui.QIcon()
        icon95.addPixmap(QtGui.QPixmap("Pictures/Bloodoak Planks.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.checkBox22_3.setIcon(icon95)
        self.checkBox22_3.setIconSize(QtCore.QSize(100, 100))
        self.checkBox22_3.setCheckable(True)
        self.checkBox22_3.setObjectName("checkBox22_3")
        self.gridLayout_8.addWidget(self.checkBox22_3, 3, 1, 1, 1, QtCore.Qt.AlignHCenter)
        self.checkBox3_3 = QtWidgets.QCheckBox(self.Into_Frame_Item_6)
        font = QtGui.QFont()
        font.setPointSize(8)
        self.checkBox3_3.setFont(font)
        self.checkBox3_3.setText("")
        icon96 = QtGui.QIcon()
        icon96.addPixmap(QtGui.QPixmap("Pictures/Lavish Cloth.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.checkBox3_3.setIcon(icon96)
        self.checkBox3_3.setIconSize(QtCore.QSize(100, 100))
        self.checkBox3_3.setCheckable(True)
        self.checkBox3_3.setObjectName("checkBox3_3")
        self.gridLayout_8.addWidget(self.checkBox3_3, 1, 1, 1, 1, QtCore.Qt.AlignHCenter)
        self.checkBox11_3 = QtWidgets.QCheckBox(self.Into_Frame_Item_6)
        font = QtGui.QFont()
        font.setPointSize(8)
        self.checkBox11_3.setFont(font)
        self.checkBox11_3.setText("")
        icon97 = QtGui.QIcon()
        icon97.addPixmap(QtGui.QPixmap("Pictures/Robust Hide.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.checkBox11_3.setIcon(icon97)
        self.checkBox11_3.setIconSize(QtCore.QSize(100, 100))
        self.checkBox11_3.setCheckable(True)
        self.checkBox11_3.setObjectName("checkBox11_3")
        self.gridLayout_8.addWidget(self.checkBox11_3, 5, 0, 1, 1, QtCore.Qt.AlignHCenter)
        self.checkBox20_3 = QtWidgets.QCheckBox(self.Into_Frame_Item_6)
        font = QtGui.QFont()
        font.setPointSize(8)
        self.checkBox20_3.setFont(font)
        self.checkBox20_3.setText("")
        icon98 = QtGui.QIcon()
        icon98.addPixmap(QtGui.QPixmap("Pictures/Bloodoak Logs.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.checkBox20_3.setIcon(icon98)
        self.checkBox20_3.setIconSize(QtCore.QSize(100, 100))
        self.checkBox20_3.setCheckable(True)
        self.checkBox20_3.setObjectName("checkBox20_3")
        self.gridLayout_8.addWidget(self.checkBox20_3, 3, 0, 1, 1, QtCore.Qt.AlignHCenter)
        self.checkBox13_4 = QtWidgets.QCheckBox(self.Into_Frame_Item_6)
        font = QtGui.QFont()
        font.setPointSize(8)
        self.checkBox13_4.setFont(font)
        self.checkBox13_4.setText("")
        icon99 = QtGui.QIcon()
        icon99.addPixmap(QtGui.QPixmap("Pictures/Amberleaf Cotton.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.checkBox13_4.setIcon(icon99)
        self.checkBox13_4.setIconSize(QtCore.QSize(100, 100))
        self.checkBox13_4.setCheckable(True)
        self.checkBox13_4.setObjectName("checkBox13_4")
        self.gridLayout_8.addWidget(self.checkBox13_4, 1, 0, 1, 1, QtCore.Qt.AlignHCenter)
        self.checkBox13_5 = QtWidgets.QCheckBox(self.Into_Frame_Item_6)
        font = QtGui.QFont()
        font.setPointSize(8)
        self.checkBox13_5.setFont(font)
        self.checkBox13_5.setText("")
        icon100 = QtGui.QIcon()
        icon100.addPixmap(QtGui.QPixmap("Pictures/Runite Steel Bar.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.checkBox13_5.setIcon(icon100)
        self.checkBox13_5.setIconSize(QtCore.QSize(100, 100))
        self.checkBox13_5.setCheckable(True)
        self.checkBox13_5.setObjectName("checkBox13_5")
        self.gridLayout_8.addWidget(self.checkBox13_5, 0, 1, 1, 1, QtCore.Qt.AlignHCenter)
        self.checkBox19_3 = QtWidgets.QCheckBox(self.Into_Frame_Item_6)
        font = QtGui.QFont()
        font.setPointSize(8)
        self.checkBox19_3.setFont(font)
        self.checkBox19_3.setText("")
        icon101 = QtGui.QIcon()
        icon101.addPixmap(QtGui.QPixmap("Pictures/Slate.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.checkBox19_3.setIcon(icon101)
        self.checkBox19_3.setIconSize(QtCore.QSize(100, 100))
        self.checkBox19_3.setCheckable(True)
        self.checkBox19_3.setObjectName("checkBox19_3")
        self.gridLayout_8.addWidget(self.checkBox19_3, 6, 0, 1, 1, QtCore.Qt.AlignHCenter)
        self.checkBox13_3 = QtWidgets.QCheckBox(self.Into_Frame_Item_6)
        font = QtGui.QFont()
        font.setPointSize(8)
        self.checkBox13_3.setFont(font)
        self.checkBox13_3.setText("")
        icon102 = QtGui.QIcon()
        icon102.addPixmap(QtGui.QPixmap("Pictures/Runite Ore.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.checkBox13_3.setIcon(icon102)
        self.checkBox13_3.setIconSize(QtCore.QSize(100, 100))
        self.checkBox13_3.setCheckable(True)
        self.checkBox13_3.setObjectName("checkBox13_3")
        self.gridLayout_8.addWidget(self.checkBox13_3, 0, 0, 1, 1, QtCore.Qt.AlignHCenter)
        self.checkBox10_3 = QtWidgets.QCheckBox(self.Into_Frame_Item_6)
        font = QtGui.QFont()
        font.setPointSize(8)
        self.checkBox10_3.setFont(font)
        self.checkBox10_3.setText("")
        icon103 = QtGui.QIcon()
        icon103.addPixmap(QtGui.QPixmap("Pictures/Hardened Leather.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.checkBox10_3.setIcon(icon103)
        self.checkBox10_3.setIconSize(QtCore.QSize(100, 100))
        self.checkBox10_3.setCheckable(True)
        self.checkBox10_3.setObjectName("checkBox10_3")
        self.gridLayout_8.addWidget(self.checkBox10_3, 5, 1, 1, 1, QtCore.Qt.AlignHCenter)
        self.checkBox24_3 = QtWidgets.QCheckBox(self.Into_Frame_Item_6)
        font = QtGui.QFont()
        font.setPointSize(8)
        self.checkBox24_3.setFont(font)
        self.checkBox24_3.setText("")
        icon104 = QtGui.QIcon()
        icon104.addPixmap(QtGui.QPixmap("Pictures/Slate Block.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.checkBox24_3.setIcon(icon104)
        self.checkBox24_3.setIconSize(QtCore.QSize(100, 100))
        self.checkBox24_3.setCheckable(True)
        self.checkBox24_3.setObjectName("checkBox24_3")
        self.gridLayout_8.addWidget(self.checkBox24_3, 6, 1, 1, 1, QtCore.Qt.AlignHCenter)
        self.Main_Frame_Item.addTab(self.tab, "")
        self.Main_Button_Frame = QtWidgets.QFrame(self.centralwidget)
        self.Main_Button_Frame.setGeometry(QtCore.QRect(0, 10, 315, 340))
        font = QtGui.QFont()
        font.setPointSize(13)
        font.setBold(False)
        font.setWeight(50)
        self.Main_Button_Frame.setFont(font)
        self.Main_Button_Frame.setObjectName("Main_Button_Frame")
        self.gridLayout = QtWidgets.QGridLayout(self.Main_Button_Frame)
        self.gridLayout.setObjectName("gridLayout")
        self.Citys = QtWidgets.QLabel(self.Main_Button_Frame)
        font = QtGui.QFont()
        font.setPointSize(24)
        self.Citys.setFont(font)
        self.Citys.setObjectName("Citys")
        self.gridLayout.addWidget(self.Citys, 0, 1, 1, 1, QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter)
        self.checkBox_Chair_2 = QtWidgets.QCheckBox(self.Main_Button_Frame)
        self.checkBox_Chair_2.setObjectName("checkBox_Chair_2")
        self.gridLayout.addWidget(self.checkBox_Chair_2, 6, 1, 1, 1, QtCore.Qt.AlignHCenter)
        self.checkBox_Chair_3 = QtWidgets.QCheckBox(self.Main_Button_Frame)
        self.checkBox_Chair_3.setObjectName("checkBox_Chair_3")
        self.gridLayout.addWidget(self.checkBox_Chair_3, 7, 1, 1, 1, QtCore.Qt.AlignHCenter)
        self.radioButton_4 = QtWidgets.QRadioButton(self.Main_Button_Frame)
        self.radioButton_4.setObjectName("radioButton_4")
        self.gridLayout.addWidget(self.radioButton_4, 7, 2, 1, 1, QtCore.Qt.AlignHCenter)
        self.radioButton_5 = QtWidgets.QRadioButton(self.Main_Button_Frame)
        self.radioButton_5.setObjectName("radioButton_5")
        self.gridLayout.addWidget(self.radioButton_5, 8, 2, 1, 1, QtCore.Qt.AlignHCenter)
        self.checkBox_Tier_8 = QtWidgets.QCheckBox(self.Main_Button_Frame)
        self.checkBox_Tier_8.setObjectName("checkBox_Tier_8")
        self.gridLayout.addWidget(self.checkBox_Tier_8, 8, 0, 1, 1, QtCore.Qt.AlignHCenter)
        self.checkBox_Chair_4 = QtWidgets.QCheckBox(self.Main_Button_Frame)
        self.checkBox_Chair_4.setObjectName("checkBox_Chair_4")
        self.gridLayout.addWidget(self.checkBox_Chair_4, 8, 1, 1, 1, QtCore.Qt.AlignHCenter)
        self.checkBox_Thetford = QtWidgets.QCheckBox(self.Main_Button_Frame)
        self.checkBox_Thetford.setObjectName("checkBox_Thetford")
        self.gridLayout.addWidget(self.checkBox_Thetford, 1, 2, 1, 1)
        self.checkBox_Caerleon = QtWidgets.QCheckBox(self.Main_Button_Frame)
        self.checkBox_Caerleon.setObjectName("checkBox_Caerleon")
        self.gridLayout.addWidget(self.checkBox_Caerleon, 1, 1, 1, 1)
        self.checkBox_Fort_Stearling = QtWidgets.QCheckBox(self.Main_Button_Frame)
        self.checkBox_Fort_Stearling.setObjectName("checkBox_Fort_Stearling")
        self.gridLayout.addWidget(self.checkBox_Fort_Stearling, 1, 0, 1, 1)
        self.label_Chair = QtWidgets.QLabel(self.Main_Button_Frame)
        self.label_Chair.setObjectName("label_Chair")
        self.gridLayout.addWidget(self.label_Chair, 3, 1, 1, 1, QtCore.Qt.AlignHCenter)
        self.label_Tier = QtWidgets.QLabel(self.Main_Button_Frame)
        self.label_Tier.setObjectName("label_Tier")
        self.gridLayout.addWidget(self.label_Tier, 3, 0, 1, 1, QtCore.Qt.AlignHCenter)
        self.checkBox_Tier_4 = QtWidgets.QCheckBox(self.Main_Button_Frame)
        self.checkBox_Tier_4.setObjectName("checkBox_Tier_4")
        self.gridLayout.addWidget(self.checkBox_Tier_4, 4, 0, 1, 1, QtCore.Qt.AlignHCenter)
        self.checkBox_Chair_0 = QtWidgets.QCheckBox(self.Main_Button_Frame)
        self.checkBox_Chair_0.setObjectName("checkBox_Chair_0")
        self.gridLayout.addWidget(self.checkBox_Chair_0, 4, 1, 1, 1, QtCore.Qt.AlignHCenter)
        self.label_Rarity = QtWidgets.QLabel(self.Main_Button_Frame)
        self.label_Rarity.setObjectName("label_Rarity")
        self.gridLayout.addWidget(self.label_Rarity, 3, 2, 1, 1, QtCore.Qt.AlignHCenter)
        self.radioButton_1 = QtWidgets.QRadioButton(self.Main_Button_Frame)
        self.radioButton_1.setObjectName("radioButton_1")
        self.gridLayout.addWidget(self.radioButton_1, 4, 2, 1, 1, QtCore.Qt.AlignHCenter)
        self.checkBox_Chair_1 = QtWidgets.QCheckBox(self.Main_Button_Frame)
        self.checkBox_Chair_1.setObjectName("checkBox_Chair_1")
        self.gridLayout.addWidget(self.checkBox_Chair_1, 5, 1, 1, 1, QtCore.Qt.AlignHCenter)
        self.checkBox_Tier_5 = QtWidgets.QCheckBox(self.Main_Button_Frame)
        self.checkBox_Tier_5.setObjectName("checkBox_Tier_5")
        self.gridLayout.addWidget(self.checkBox_Tier_5, 5, 0, 1, 1, QtCore.Qt.AlignHCenter)
        self.checkBox_Tier_6 = QtWidgets.QCheckBox(self.Main_Button_Frame)
        self.checkBox_Tier_6.setObjectName("checkBox_Tier_6")
        self.gridLayout.addWidget(self.checkBox_Tier_6, 6, 0, 1, 1, QtCore.Qt.AlignHCenter)
        self.radioButton_2 = QtWidgets.QRadioButton(self.Main_Button_Frame)
        self.radioButton_2.setObjectName("radioButton_2")
        self.gridLayout.addWidget(self.radioButton_2, 5, 2, 1, 1, QtCore.Qt.AlignHCenter)
        self.radioButton_3 = QtWidgets.QRadioButton(self.Main_Button_Frame)
        self.radioButton_3.setObjectName("radioButton_3")
        self.gridLayout.addWidget(self.radioButton_3, 6, 2, 1, 1, QtCore.Qt.AlignHCenter)
        self.checkBox_Tier_7 = QtWidgets.QCheckBox(self.Main_Button_Frame)
        self.checkBox_Tier_7.setObjectName("checkBox_Tier_7")
        self.gridLayout.addWidget(self.checkBox_Tier_7, 7, 0, 1, 1, QtCore.Qt.AlignHCenter)
        self.checkBox_Lymhurst = QtWidgets.QCheckBox(self.Main_Button_Frame)
        self.checkBox_Lymhurst.setObjectName("checkBox_Lymhurst")
        self.gridLayout.addWidget(self.checkBox_Lymhurst, 2, 0, 1, 1)
        self.checkBox_Martlock = QtWidgets.QCheckBox(self.Main_Button_Frame)
        self.checkBox_Martlock.setObjectName("checkBox_Martlock")
        self.gridLayout.addWidget(self.checkBox_Martlock, 2, 2, 1, 1)
        self.checkBox_Bridgewatch = QtWidgets.QCheckBox(self.Main_Button_Frame)
        self.checkBox_Bridgewatch.setObjectName("checkBox_Bridgewatch")
        self.gridLayout.addWidget(self.checkBox_Bridgewatch, 2, 1, 1, 1)
        self.horizontalFrame = QtWidgets.QFrame(self.centralwidget)
        self.horizontalFrame.setGeometry(QtCore.QRect(5, 350, 315, 41))
        self.horizontalFrame.setObjectName("horizontalFrame")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.horizontalFrame)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.pushButton_Start = QtWidgets.QPushButton(self.horizontalFrame)
        self.pushButton_Start.setObjectName("pushButton_Start")
        self.horizontalLayout.addWidget(self.pushButton_Start)
        self.pushButton_Exit = QtWidgets.QPushButton(self.horizontalFrame)
        self.pushButton_Exit.setObjectName("pushButton_Exit")
        self.horizontalLayout.addWidget(self.pushButton_Exit)
        self.horizontalFrame_2 = QtWidgets.QFrame(self.centralwidget)
        self.horizontalFrame_2.setGeometry(QtCore.QRect(5, 379, 315, 50))
        self.horizontalFrame_2.setObjectName("horizontalFrame_2")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.horizontalFrame_2)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.radioButton_6 = QtWidgets.QRadioButton(self.horizontalFrame_2)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.radioButton_6.setFont(font)
        self.radioButton_6.setObjectName("radioButton_6")
        self.horizontalLayout_2.addWidget(self.radioButton_6, 0, QtCore.Qt.AlignHCenter)
        self.radioButton = QtWidgets.QRadioButton(self.horizontalFrame_2)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.radioButton.setFont(font)
        self.radioButton.setObjectName("radioButton")
        self.horizontalLayout_2.addWidget(self.radioButton, 0, QtCore.Qt.AlignHCenter)
        self.comboBox = QtWidgets.QComboBox(self.centralwidget)
        self.comboBox.setGeometry(QtCore.QRect(10, 450, 300, 25))
        self.comboBox.setObjectName("comboBox")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.gridFrame = QtWidgets.QFrame(self.centralwidget)
        self.gridFrame.setGeometry(QtCore.QRect(10, 483, 310, 417))
        self.gridFrame.setObjectName("gridFrame")
        self.gridLayout_6 = QtWidgets.QGridLayout(self.gridFrame)
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.label_11 = QtWidgets.QLabel(self.gridFrame)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label_11.setFont(font)
        self.label_11.setObjectName("label_11")
        self.gridLayout_6.addWidget(self.label_11, 8, 1, 1, 1)
        self.Box_city_2 = QtWidgets.QComboBox(self.gridFrame)
        self.Box_city_2.setObjectName("Box_city_2")
        self.gridLayout_6.addWidget(self.Box_city_2, 0, 2, 1, 1, QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_MIN_S = QtWidgets.QLabel(self.gridFrame)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_MIN_S.setFont(font)
        self.label_MIN_S.setObjectName("label_MIN_S")
        self.gridLayout_6.addWidget(self.label_MIN_S, 1, 0, 1, 1)
        self.label_MIN_B = QtWidgets.QLabel(self.gridFrame)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_MIN_B.setFont(font)
        self.label_MIN_B.setObjectName("label_MIN_B")
        self.gridLayout_6.addWidget(self.label_MIN_B, 7, 0, 1, 1)
        self.label_MAX_B = QtWidgets.QLabel(self.gridFrame)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_MAX_B.setFont(font)
        self.label_MAX_B.setObjectName("label_MAX_B")
        self.gridLayout_6.addWidget(self.label_MAX_B, 9, 0, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.gridFrame)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.gridLayout_6.addWidget(self.label_3, 2, 1, 1, 1)
        self.label_MAX_DAT_B = QtWidgets.QLabel(self.gridFrame)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_MAX_DAT_B.setFont(font)
        self.label_MAX_DAT_B.setObjectName("label_MAX_DAT_B")
        self.gridLayout_6.addWidget(self.label_MAX_DAT_B, 10, 0, 1, 1)
        self.label_9 = QtWidgets.QLabel(self.gridFrame)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_9.setFont(font)
        self.label_9.setObjectName("label_9")
        self.gridLayout_6.addWidget(self.label_9, 7, 1, 1, 1)
        self.label_10 = QtWidgets.QLabel(self.gridFrame)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_10.setFont(font)
        self.label_10.setObjectName("label_10")
        self.gridLayout_6.addWidget(self.label_10, 7, 2, 1, 1)
        self.label_MIN_DAT_B = QtWidgets.QLabel(self.gridFrame)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_MIN_DAT_B.setFont(font)
        self.label_MIN_DAT_B.setObjectName("label_MIN_DAT_B")
        self.gridLayout_6.addWidget(self.label_MIN_DAT_B, 8, 0, 1, 1)
        self.MAX_DAT_S = QtWidgets.QLabel(self.gridFrame)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.MAX_DAT_S.setFont(font)
        self.MAX_DAT_S.setObjectName("MAX_DAT_S")
        self.gridLayout_6.addWidget(self.MAX_DAT_S, 4, 0, 1, 1)
        self.Box_city_1 = QtWidgets.QComboBox(self.gridFrame)
        font = QtGui.QFont()
        font.setPointSize(8)
        self.Box_city_1.setFont(font)
        self.Box_city_1.setObjectName("Box_city_1")
        self.gridLayout_6.addWidget(self.Box_city_1, 0, 1, 1, 1, QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_7 = QtWidgets.QLabel(self.gridFrame)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label_7.setFont(font)
        self.label_7.setObjectName("label_7")
        self.gridLayout_6.addWidget(self.label_7, 4, 1, 1, 1)
        self.label_8 = QtWidgets.QLabel(self.gridFrame)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label_8.setFont(font)
        self.label_8.setObjectName("label_8")
        self.gridLayout_6.addWidget(self.label_8, 4, 2, 1, 1)
        self.label_MIN_DAT_S = QtWidgets.QLabel(self.gridFrame)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_MIN_DAT_S.setFont(font)
        self.label_MIN_DAT_S.setObjectName("label_MIN_DAT_S")
        self.gridLayout_6.addWidget(self.label_MIN_DAT_S, 2, 0, 1, 1)
        self.label_MAX_S = QtWidgets.QLabel(self.gridFrame)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_MAX_S.setFont(font)
        self.label_MAX_S.setObjectName("label_MAX_S")
        self.gridLayout_6.addWidget(self.label_MAX_S, 3, 0, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.gridFrame)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.gridLayout_6.addWidget(self.label_2, 1, 2, 1, 1)
        self.label_6 = QtWidgets.QLabel(self.gridFrame)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.gridLayout_6.addWidget(self.label_6, 3, 2, 1, 1)
        self.label_4 = QtWidgets.QLabel(self.gridFrame)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.gridLayout_6.addWidget(self.label_4, 2, 2, 1, 1)
        self.label_1 = QtWidgets.QLabel(self.gridFrame)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_1.setFont(font)
        self.label_1.setObjectName("label_1")
        self.gridLayout_6.addWidget(self.label_1, 1, 1, 1, 1)
        self.label_5 = QtWidgets.QLabel(self.gridFrame)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.gridLayout_6.addWidget(self.label_5, 3, 1, 1, 1)
        self.label_14 = QtWidgets.QLabel(self.gridFrame)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_14.setFont(font)
        self.label_14.setObjectName("label_14")
        self.gridLayout_6.addWidget(self.label_14, 9, 2, 1, 1)
        self.label_13 = QtWidgets.QLabel(self.gridFrame)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_13.setFont(font)
        self.label_13.setObjectName("label_13")
        self.gridLayout_6.addWidget(self.label_13, 9, 1, 1, 1)
        self.label_12 = QtWidgets.QLabel(self.gridFrame)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label_12.setFont(font)
        self.label_12.setObjectName("label_12")
        self.gridLayout_6.addWidget(self.label_12, 8, 2, 1, 1)
        self.label_15 = QtWidgets.QLabel(self.gridFrame)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label_15.setFont(font)
        self.label_15.setObjectName("label_15")
        self.gridLayout_6.addWidget(self.label_15, 10, 1, 1, 1)
        self.label_16 = QtWidgets.QLabel(self.gridFrame)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label_16.setFont(font)
        self.label_16.setObjectName("label_16")
        self.gridLayout_6.addWidget(self.label_16, 10, 2, 1, 1)
        self.line = QtWidgets.QFrame(self.gridFrame)
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.gridLayout_6.addWidget(self.line, 6, 1, 1, 1)
        self.line_2 = QtWidgets.QFrame(self.gridFrame)
        self.line_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.gridLayout_6.addWidget(self.line_2, 6, 0, 1, 1)
        self.line_3 = QtWidgets.QFrame(self.gridFrame)
        self.line_3.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_3.setObjectName("line_3")
        self.gridLayout_6.addWidget(self.line_3, 6, 2, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        self.Main_Frame_Item.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)


        self.All_buttons_Clotch_Armor = QButtonGroup()
        self.All_buttons_Clotch_Armor.setExclusive(False)
        
        self.All_buttons_Clotch_Armor.addButton(self.checkBox1, 0)
        self.All_buttons_Clotch_Armor.addButton(self.checkBox2, 1)
        self.All_buttons_Clotch_Armor.addButton(self.checkBox3, 2)
        self.All_buttons_Clotch_Armor.addButton(self.checkBox4, 3)
        self.All_buttons_Clotch_Armor.addButton(self.checkBox5, 4)
        self.All_buttons_Clotch_Armor.addButton(self.checkBox6, 5)
        self.All_buttons_Clotch_Armor.addButton(self.checkBox7, 6)
        self.All_buttons_Clotch_Armor.addButton(self.checkBox8, 7)
        self.All_buttons_Clotch_Armor.addButton(self.checkBox9, 8)

        self.All_buttons_Clotch_Armor.addButton(self.checkBox10, 9)
        self.All_buttons_Clotch_Armor.addButton(self.checkBox11, 10)
        self.All_buttons_Clotch_Armor.addButton(self.checkBox12, 11)
        self.All_buttons_Clotch_Armor.addButton(self.checkBox13, 12)
        self.All_buttons_Clotch_Armor.addButton(self.checkBox14, 13)
        self.All_buttons_Clotch_Armor.addButton(self.checkBox15, 14)
        self.All_buttons_Clotch_Armor.addButton(self.checkBox16, 15)
        self.All_buttons_Clotch_Armor.addButton(self.checkBox17, 16)
        self.All_buttons_Clotch_Armor.addButton(self.checkBox18, 17)

        self.All_buttons_Clotch_Armor.addButton(self.checkBox19, 18)
        self.All_buttons_Clotch_Armor.addButton(self.checkBox20, 19)
        self.All_buttons_Clotch_Armor.addButton(self.checkBox21, 20)
        self.All_buttons_Clotch_Armor.addButton(self.checkBox22, 21)
        self.All_buttons_Clotch_Armor.addButton(self.checkBox23, 22)
        self.All_buttons_Clotch_Armor.addButton(self.checkBox24, 23)
        self.All_buttons_Clotch_Armor.addButton(self.checkBox25, 24)
        self.All_buttons_Clotch_Armor.addButton(self.checkBox26, 25)
        self.All_buttons_Clotch_Armor.addButton(self.checkBox27, 26)

        self.All_buttons_Leather_Armor = QButtonGroup()
        self.All_buttons_Leather_Armor.setExclusive(False)

        self.All_buttons_Leather_Armor.addButton(self.checkBox28, 0)
        self.All_buttons_Leather_Armor.addButton(self.checkBox29, 1)
        self.All_buttons_Leather_Armor.addButton(self.checkBox30, 2)
        self.All_buttons_Leather_Armor.addButton(self.checkBox31, 3)
        self.All_buttons_Leather_Armor.addButton(self.checkBox32, 4)
        self.All_buttons_Leather_Armor.addButton(self.checkBox33, 5)
        self.All_buttons_Leather_Armor.addButton(self.checkBox34, 6)
        self.All_buttons_Leather_Armor.addButton(self.checkBox35, 7)
        self.All_buttons_Leather_Armor.addButton(self.checkBox36, 8)

        self.All_buttons_Leather_Armor.addButton(self.checkBox37, 9)
        self.All_buttons_Leather_Armor.addButton(self.checkBox38, 10)
        self.All_buttons_Leather_Armor.addButton(self.checkBox39, 11)
        self.All_buttons_Leather_Armor.addButton(self.checkBox40, 12)
        self.All_buttons_Leather_Armor.addButton(self.checkBox41, 13)
        self.All_buttons_Leather_Armor.addButton(self.checkBox42, 14)
        self.All_buttons_Leather_Armor.addButton(self.checkBox43, 15)
        self.All_buttons_Leather_Armor.addButton(self.checkBox44, 16)
        self.All_buttons_Leather_Armor.addButton(self.checkBox45, 17)

        self.All_buttons_Leather_Armor.addButton(self.checkBox46, 18)
        self.All_buttons_Leather_Armor.addButton(self.checkBox47, 19)
        self.All_buttons_Leather_Armor.addButton(self.checkBox48, 20)
        self.All_buttons_Leather_Armor.addButton(self.checkBox49, 21)
        self.All_buttons_Leather_Armor.addButton(self.checkBox50, 22)
        self.All_buttons_Leather_Armor.addButton(self.checkBox51, 23)
        self.All_buttons_Leather_Armor.addButton(self.checkBox52, 24)
        self.All_buttons_Leather_Armor.addButton(self.checkBox53, 25)
        self.All_buttons_Leather_Armor.addButton(self.checkBox54, 26)

        self.All_buttons_Plate_Armor = QButtonGroup()
        self.All_buttons_Plate_Armor.setExclusive(False)

        self.All_buttons_Plate_Armor.addButton(self.checkBox55, 0)
        self.All_buttons_Plate_Armor.addButton(self.checkBox56, 1)
        self.All_buttons_Plate_Armor.addButton(self.checkBox57, 2)
        self.All_buttons_Plate_Armor.addButton(self.checkBox58, 3)
        self.All_buttons_Plate_Armor.addButton(self.checkBox59, 4)
        self.All_buttons_Plate_Armor.addButton(self.checkBox60, 5)
        self.All_buttons_Plate_Armor.addButton(self.checkBox61, 6)
        self.All_buttons_Plate_Armor.addButton(self.checkBox62, 7)
        self.All_buttons_Plate_Armor.addButton(self.checkBox63, 8)

        self.All_buttons_Plate_Armor.addButton(self.checkBox64, 9)
        self.All_buttons_Plate_Armor.addButton(self.checkBox65, 10)
        self.All_buttons_Plate_Armor.addButton(self.checkBox66, 11)
        self.All_buttons_Plate_Armor.addButton(self.checkBox67, 12)
        self.All_buttons_Plate_Armor.addButton(self.checkBox68, 13)
        self.All_buttons_Plate_Armor.addButton(self.checkBox69, 14)
        self.All_buttons_Plate_Armor.addButton(self.checkBox70, 15)
        self.All_buttons_Plate_Armor.addButton(self.checkBox71, 16)
        self.All_buttons_Plate_Armor.addButton(self.checkBox72, 17)

        self.All_buttons_Plate_Armor.addButton(self.checkBox73, 18)
        self.All_buttons_Plate_Armor.addButton(self.checkBox74, 19)
        self.All_buttons_Plate_Armor.addButton(self.checkBox75, 20)
        self.All_buttons_Plate_Armor.addButton(self.checkBox76, 21)
        self.All_buttons_Plate_Armor.addButton(self.checkBox77, 22)
        self.All_buttons_Plate_Armor.addButton(self.checkBox78, 23)
        self.All_buttons_Plate_Armor.addButton(self.checkBox79, 24)
        self.All_buttons_Plate_Armor.addButton(self.checkBox80, 25)
        self.All_buttons_Plate_Armor.addButton(self.checkBox81, 26)
        

        self.All_tier_group = QButtonGroup()
        self.All_tier_group.setExclusive(False)
        self.All_tier_group.addButton(self.checkBox_Tier_4, 0)
        self.All_tier_group.addButton(self.checkBox_Tier_5, 1)
        self.All_tier_group.addButton(self.checkBox_Tier_6, 2)
        self.All_tier_group.addButton(self.checkBox_Tier_7, 3)
        self.All_tier_group.addButton(self.checkBox_Tier_8, 4)

        self.All_rarity_group = QButtonGroup()
        self.All_rarity_group.setExclusive(False)
        self.All_rarity_group.addButton(self.checkBox_Chair_0, 0)
        self.All_rarity_group.addButton(self.checkBox_Chair_1, 1)
        self.All_rarity_group.addButton(self.checkBox_Chair_2, 2)
        self.All_rarity_group.addButton(self.checkBox_Chair_3, 3)
        self.All_rarity_group.addButton(self.checkBox_Chair_4, 4)

        self.All_qualities_group = QButtonGroup()
        self.All_qualities_group.addButton(self.radioButton_1, 1)
        self.All_qualities_group.addButton(self.radioButton_2, 2)
        self.All_qualities_group.addButton(self.radioButton_3, 3)
        self.All_qualities_group.addButton(self.radioButton_4, 4)
        self.All_qualities_group.addButton(self.radioButton_5, 5)

        self.All_Citys_group = QButtonGroup()
        self.All_Citys_group.setExclusive(False)
        self.All_Citys_group.addButton(self.checkBox_Caerleon, 0)
        self.All_Citys_group.addButton(self.checkBox_Fort_Stearling, 1)
        self.All_Citys_group.addButton(self.checkBox_Martlock, 2)
        self.All_Citys_group.addButton(self.checkBox_Lymhurst, 3)
        self.All_Citys_group.addButton(self.checkBox_Bridgewatch, 4)

        self.Lable_Group_1 = list()
        self.Lable_Group_1.append(self.label_1)
        self.Lable_Group_1.append(self.label_3)
        self.Lable_Group_1.append(self.label_5)
        self.Lable_Group_1.append(self.label_7)
        self.Lable_Group_1.append(self.label_9)
        self.Lable_Group_1.append(self.label_11)
        self.Lable_Group_1.append(self.label_13)
        self.Lable_Group_1.append(self.label_15)
        
        self.Lable_Group_2 = list()
        self.Lable_Group_2.append(self.label_2)
        self.Lable_Group_2.append(self.label_4)
        self.Lable_Group_2.append(self.label_6)
        self.Lable_Group_2.append(self.label_8)
        self.Lable_Group_1.append(self.label_10)
        self.Lable_Group_1.append(self.label_12)
        self.Lable_Group_1.append(self.label_14)
        self.Lable_Group_1.append(self.label_16)
        

        self.button_funckshens()
        

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.Main_Frame_Item.setTabText(self.Main_Frame_Item.indexOf(self.Clotch), _translate("MainWindow", "Тканевая Б."))
        self.Main_Frame_Item.setTabText(self.Main_Frame_Item.indexOf(self.Kozaa), _translate("MainWindow", "Кожаная Б."))
        self.Main_Frame_Item.setTabText(self.Main_Frame_Item.indexOf(self.Lat), _translate("MainWindow", "Латная Б."))
        self.Main_Frame_Item.setTabText(self.Main_Frame_Item.indexOf(self.Bags), _translate("MainWindow", "Шмотки"))
        self.Main_Frame_Item.setTabText(self.Main_Frame_Item.indexOf(self.tab), _translate("MainWindow", "Ресурсы"))
        self.Citys.setText(_translate("MainWindow", "Город"))
        self.checkBox_Chair_2.setText(_translate("MainWindow", "2"))
        self.checkBox_Chair_3.setText(_translate("MainWindow", "3"))
        self.radioButton_4.setText(_translate("MainWindow", "Отличное"))
        self.radioButton_5.setText(_translate("MainWindow", "Шедевр"))
        self.checkBox_Tier_8.setText(_translate("MainWindow", "8"))
        self.checkBox_Chair_4.setText(_translate("MainWindow", "4"))
        self.checkBox_Thetford.setText(_translate("MainWindow", "Thetford"))
        self.checkBox_Caerleon.setText(_translate("MainWindow", "Caerleon"))
        self.checkBox_Fort_Stearling.setText(_translate("MainWindow", "Fort Stearling"))
        self.label_Chair.setText(_translate("MainWindow", "Зачар"))
        self.label_Tier.setText(_translate("MainWindow", "Тир"))
        self.checkBox_Tier_4.setText(_translate("MainWindow", "4"))
        self.checkBox_Chair_0.setText(_translate("MainWindow", "0"))
        self.label_Rarity.setText(_translate("MainWindow", "Качество"))
        self.radioButton_1.setText(_translate("MainWindow", "Обычное"))
        self.checkBox_Chair_1.setText(_translate("MainWindow", "1"))
        self.checkBox_Tier_5.setText(_translate("MainWindow", "5"))
        self.checkBox_Tier_6.setText(_translate("MainWindow", "6"))
        self.radioButton_2.setText(_translate("MainWindow", "Хорошое"))
        self.radioButton_3.setText(_translate("MainWindow", "Выдающ"))
        self.checkBox_Tier_7.setText(_translate("MainWindow", "7"))
        self.checkBox_Lymhurst.setText(_translate("MainWindow", "Lymhurst"))
        self.checkBox_Martlock.setText(_translate("MainWindow", "Martlok"))
        self.checkBox_Bridgewatch.setText(_translate("MainWindow", "Bridgewatch"))
        self.pushButton_Start.setText(_translate("MainWindow", "Start"))
        self.pushButton_Exit.setText(_translate("MainWindow", "Exit"))
        self.radioButton_6.setText(_translate("MainWindow", "Open in Browzer"))
        self.radioButton.setText(_translate("MainWindow", "Open in Data"))
        self.label_11.setText(_translate("MainWindow", "TextLabel"))
        self.label_MIN_S.setText(_translate("MainWindow", "MIN_S"))
        self.label_MIN_B.setText(_translate("MainWindow", "MIN_B"))
        self.label_MAX_B.setText(_translate("MainWindow", "MAX_B"))
        self.label_3.setText(_translate("MainWindow", "TextLabel"))
        self.label_MAX_DAT_B.setText(_translate("MainWindow", "MAX_DAT_B"))
        self.label_9.setText(_translate("MainWindow", "TextLabel"))
        self.label_10.setText(_translate("MainWindow", "TextLabel"))
        self.label_MIN_DAT_B.setText(_translate("MainWindow", "MIN_DAT_B"))
        self.MAX_DAT_S.setText(_translate("MainWindow", "MAX_DAT_S"))
        self.label_7.setText(_translate("MainWindow", "TextLabel"))
        self.label_8.setText(_translate("MainWindow", "TextLabel"))
        self.label_MIN_DAT_S.setText(_translate("MainWindow", "MIN_DAT_S"))
        self.label_MAX_S.setText(_translate("MainWindow", "MAX_S"))
        self.label_2.setText(_translate("MainWindow", "TextLabel"))
        self.label_6.setText(_translate("MainWindow", "TextLabel"))
        self.label_4.setText(_translate("MainWindow", "TextLabel"))
        self.label_1.setText(_translate("MainWindow", "TextLabel"))
        self.label_5.setText(_translate("MainWindow", "TextLabel"))
        self.label_14.setText(_translate("MainWindow", "TextLabel"))
        self.label_13.setText(_translate("MainWindow", "TextLabel"))
        self.label_12.setText(_translate("MainWindow", "TextLabel"))
        self.label_15.setText(_translate("MainWindow", "TextLabel"))
        self.label_16.setText(_translate("MainWindow", "TextLabel"))


    def button_funckshens(self):

        self.comboBox.activated[str].connect(lambda: self.Info(3))
        self.Box_city_1.activated[str].connect(lambda: self.Info(1))
        self.Box_city_2.activated[str].connect(lambda: self.Info(2))

        self.main_button(self.All_buttons_Clotch_Armor, List_item.Clotch_Armor)
        self.main_button(self.All_buttons_Leather_Armor, List_item.Leather_Armor)
        self.main_button(self.All_buttons_Plate_Armor, List_item.Plate_Armor)
        
        self.All_tier_group.buttonClicked[int].connect(self.tier_add)
        self.All_rarity_group.buttonClicked[int].connect(self.Rarity_add)
        self.All_qualities_group.buttonClicked[int].connect(self.Qualities_changing)
        self.All_Citys_group.buttonClicked[int].connect(self.City_add)

        self.pushButton_Start.clicked.connect(lambda: self.stats())
        self.pushButton_Exit.clicked.connect(lambda: self.exit())

    
    def main_button(self, group_button: list, item_list: list):
        def check_butt(butt_id):
            #Получение id кнопки
            for btn in group_button.buttons():
                if btn is group_button.button(butt_id):
                    
                    #Добавление предмета в список
                    if item_list[butt_id] in Item_list_f: 
                        Item_list_f.remove(item_list[butt_id])
                    #Удаление предмета со списка
                    else: 
                        Item_list_f.append(item_list[butt_id])
            
        group_button.buttonClicked[int].connect(check_butt)


    def end_list(self):
        global Item_list_f, Item_list_s
        Item_list_s.clear()
        
        for item in Item_list_f:
            for tier in Tier_list:
                for rarity in Rarity_list:
        
                    Item_list_s.append( tier + item + rarity )


    def tier_add(self, button_id: int):

        for btn in self.All_tier_group.buttons():
            if btn is self.All_tier_group.button(button_id):

                if Tiers[button_id] in Tier_list:
                    Tier_list.remove(Tiers[button_id])
                    Tier_list.sort()
                else:
                    Tier_list.append(Tiers[button_id])
                    Tier_list.sort()


    def Rarity_add(self, button_id: int):

        for btn in self.All_rarity_group.buttons():
            if btn is self.All_rarity_group.button(button_id):

                if Rarytyes[button_id] in Rarity_list:
                    Rarity_list.remove(Rarytyes[button_id])
                    Rarity_list.sort()
                else:
                    Rarity_list.append(Rarytyes[button_id])
                    Rarity_list.sort()


    def City_add(self, button_id: int):

        for btn in self.All_Citys_group.buttons():
            if btn is self.All_Citys_group.button(button_id):

                if locations[button_id] in locations_list:
                    locations_list.remove(locations[button_id])
                    locations_list.sort()
                else:
                    locations_list.append(locations[button_id])
                    locations_list.sort()


    def Qualities_changing(self, button_id: int):
        global qualities
        qualities = button_id


    def Info(self, num_lable):
                    
        for item in Item_list_s:

            if num_lable == 1:
                if self.comboBox.currentText() == item.item_id:
                    if self.Box_city_1.currentText() == item.city:
                        self.label_1.setText(item.sell_price_min)
                        self.label_3.setText(item.sell_price_min_date)
                        self.label_5.setText(item.sell_price_max)
                        self.label_7.setText(item.sell_price_min_date)
                        self.label_9.setText(item.buy_price_min)
                        self.label_11.setText(item.buy_price_min_date)
                        self.label_13.setText(item.buy_price_max)
                        self.label_15.setText(item.buy_price_min_date)

            elif num_lable == 2:
                if self.comboBox.currentText() == item.item_id:
                    if self.Box_city_2.currentText() == item.city:
                        self.label_2.setText(item.sell_price_min)
                        self.label_4.setText(item.sell_price_min_date)
                        self.label_6.setText(item.sell_price_max)
                        self.label_8.setText(item.sell_price_min_date)
                        self.label_10.setText(item.buy_price_min)
                        self.label_12.setText(item.buy_price_min_date)
                        self.label_14.setText(item.buy_price_max)
                        self.label_16.setText(item.buy_price_min_date)
        
            elif num_lable == 3:
                self.Info(1)
                self.Info(2)


    def stats(self):
        self.end_list()
        if len(Tier_list) > 0 and len(Rarity_list) > 0 and len(locations_list) > 0 and qualities > 0:
            URL = stock + ','. join(Item_list_s) + location + ','. join(locations_list) + qualities_url + str(qualities)

            self.comboBox.clear()
            self.Box_city_1.clear()
            self.Box_city_2.clear()
            for item in Item_list_s: self.comboBox.addItem(item)
            for city in locations_list: 
                if city == 'Fortsterling': city = 'Fort Sterling'
                self.Box_city_1.addItem(city), self.Box_city_2.addItem(city)

            if self.radioButton_6.isChecked(): webbrowser.open_new(URL)
            
            
            Pr_list, = pandas.read_html(URL, header=0, parse_dates=['item_id'])
            Pr_list.to_excel("Prises.xlsx")
            Pr_list.to_json('Prises.json', date_format="iso", indent=4)

            if self.radioButton.isChecked(): pass

    def exit(self):
        sys.exit()


stock = 'https://www.albion-online-data.com/api/v2/stats/view/'

location = '?locations='

locations = ['Caerleon','Fortsterling','Martlock','Thetford','Lymhurst','Bridgewatch']
locations_list = []

qualities_url = '&qualities=' 
City_url = '?locations='

Item_list_f = []
Item_list_s = []

Tier_list = []
Rarity_list = []

Tiers = ['T4_', 'T5_', 'T6_', 'T7_', 'T8_']
Rarytyes = ['', '@1', '@2', '@3', '@4']


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
