import os, json, pandas, webbrowser

from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import QButtonGroup
from datetime import datetime

import List_item

from Sort_Data import Ui_MainWindow_2


qualities = 1

class Ui_MainWindow(object):
    def Open_Program(self):
        self.window = QtWidgets.QMainWindow()
        self.ui = Ui_MainWindow_2()
        self.ui.setupUi(self.window)
        self.window.show()


    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(750, 810)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.Main_Frame_Item = QtWidgets.QTabWidget(self.centralwidget)
        self.Main_Frame_Item.setGeometry(QtCore.QRect(320, 3, 425, 870))
        self.Main_Frame_Item.setObjectName("Main_Frame_Item")
        self.Clotch = QtWidgets.QWidget()
        self.Clotch.setObjectName("Clotch")
        self.Into_Frame_Item_1 = QtWidgets.QFrame(self.Clotch)
        self.Into_Frame_Item_1.setGeometry(QtCore.QRect(5, -3, 460, 800))
        self.Into_Frame_Item_1.setObjectName("Into_Frame_Item_1")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.Into_Frame_Item_1)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.checkBox19 = QtWidgets.QCheckBox(self.Into_Frame_Item_1)
        self.checkBox19.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("C:\\Albion_Progect\\Albion_Progect\\Pictures/T6_SHOES_CLOTH_SET1@0.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.checkBox19.setIcon(icon)
        self.checkBox19.setIconSize(QtCore.QSize(90, 90))
        self.checkBox19.setCheckable(True)
        self.checkBox19.setObjectName("checkBox19")
        self.gridLayout_2.addWidget(self.checkBox19, 1, 4, 1, 1)
        self.checkBox1 = QtWidgets.QCheckBox(self.Into_Frame_Item_1)
        self.checkBox1.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("C:\\Albion_Progect\\Albion_Progect\\Pictures/T6_HEAD_CLOTH_SET1@0.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.checkBox1.setIcon(icon1)
        self.checkBox1.setIconSize(QtCore.QSize(90, 90))
        self.checkBox1.setCheckable(True)
        self.checkBox1.setObjectName("checkBox1")
        self.gridLayout_2.addWidget(self.checkBox1, 1, 0, 1, 1)
        self.checkBox14 = QtWidgets.QCheckBox(self.Into_Frame_Item_1)
        self.checkBox14.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("C:\\Albion_Progect\\Albion_Progect\\Pictures/T6_ARMOR_CLOTH_ROYAL.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.checkBox14.setIcon(icon2)
        self.checkBox14.setIconSize(QtCore.QSize(90, 90))
        self.checkBox14.setCheckable(True)
        self.checkBox14.setObjectName("checkBox14")
        self.gridLayout_2.addWidget(self.checkBox14, 5, 2, 1, 1)
        self.checkBox23 = QtWidgets.QCheckBox(self.Into_Frame_Item_1)
        self.checkBox23.setText("")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap("C:\\Albion_Progect\\Albion_Progect\\Pictures/T6_SHOES_CLOTH_ROYAL@0.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.checkBox23.setIcon(icon3)
        self.checkBox23.setIconSize(QtCore.QSize(90, 90))
        self.checkBox23.setCheckable(True)
        self.checkBox23.setObjectName("checkBox23")
        self.gridLayout_2.addWidget(self.checkBox23, 5, 4, 1, 1)
        self.checkBox10 = QtWidgets.QCheckBox(self.Into_Frame_Item_1)
        self.checkBox10.setText("")
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap("C:\\Albion_Progect\\Albion_Progect\\Pictures/T6_ARMOR_CLOTH_SET1.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.checkBox10.setIcon(icon4)
        self.checkBox10.setIconSize(QtCore.QSize(90, 90))
        self.checkBox10.setCheckable(True)
        self.checkBox10.setObjectName("checkBox10")
        self.gridLayout_2.addWidget(self.checkBox10, 1, 2, 1, 1)
        self.checkBox13 = QtWidgets.QCheckBox(self.Into_Frame_Item_1)
        self.checkBox13.setText("")
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap("C:\\Albion_Progect\\Albion_Progect\\Pictures/T6_ARMOR_CLOTH_KEEPER.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.checkBox13.setIcon(icon5)
        self.checkBox13.setIconSize(QtCore.QSize(90, 90))
        self.checkBox13.setCheckable(True)
        self.checkBox13.setObjectName("checkBox13")
        self.gridLayout_2.addWidget(self.checkBox13, 4, 2, 1, 1)
        self.checkBox11 = QtWidgets.QCheckBox(self.Into_Frame_Item_1)
        self.checkBox11.setText("")
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap("C:\\Albion_Progect\\Albion_Progect\\Pictures/T6_ARMOR_CLOTH_SET3.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.checkBox11.setIcon(icon6)
        self.checkBox11.setIconSize(QtCore.QSize(90, 90))
        self.checkBox11.setCheckable(True)
        self.checkBox11.setObjectName("checkBox11")
        self.gridLayout_2.addWidget(self.checkBox11, 2, 2, 1, 1)
        self.checkBox18 = QtWidgets.QCheckBox(self.Into_Frame_Item_1)
        self.checkBox18.setText("")
        icon7 = QtGui.QIcon()
        icon7.addPixmap(QtGui.QPixmap("C:\\Albion_Progect\\Albion_Progect\\Pictures/T6_ARMOR_CLOTH_FEY@0.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.checkBox18.setIcon(icon7)
        self.checkBox18.setIconSize(QtCore.QSize(90, 90))
        self.checkBox18.setCheckable(True)
        self.checkBox18.setObjectName("checkBox18")
        self.gridLayout_2.addWidget(self.checkBox18, 9, 2, 1, 1)
        self.checkBox15 = QtWidgets.QCheckBox(self.Into_Frame_Item_1)
        self.checkBox15.setText("")
        icon8 = QtGui.QIcon()
        icon8.addPixmap(QtGui.QPixmap("C:\\Albion_Progect\\Albion_Progect\\Pictures/T6_ARMOR_CLOTH_HELL@0.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.checkBox15.setIcon(icon8)
        self.checkBox15.setIconSize(QtCore.QSize(90, 90))
        self.checkBox15.setCheckable(True)
        self.checkBox15.setObjectName("checkBox15")
        self.gridLayout_2.addWidget(self.checkBox15, 6, 2, 1, 1)
        self.checkBox17 = QtWidgets.QCheckBox(self.Into_Frame_Item_1)
        self.checkBox17.setText("")
        icon9 = QtGui.QIcon()
        icon9.addPixmap(QtGui.QPixmap("C:\\Albion_Progect\\Albion_Progect\\Pictures/T6_ARMOR_CLOTH_AVALON@0.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.checkBox17.setIcon(icon9)
        self.checkBox17.setIconSize(QtCore.QSize(90, 90))
        self.checkBox17.setCheckable(True)
        self.checkBox17.setObjectName("checkBox17")
        self.gridLayout_2.addWidget(self.checkBox17, 8, 2, 1, 1)
        self.checkBox12 = QtWidgets.QCheckBox(self.Into_Frame_Item_1)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.checkBox12.setFont(font)
        self.checkBox12.setText("")
        icon10 = QtGui.QIcon()
        icon10.addPixmap(QtGui.QPixmap("C:\\Albion_Progect\\Albion_Progect\\Pictures/T6_ARMOR_CLOTH_SET2.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.checkBox12.setIcon(icon10)
        self.checkBox12.setIconSize(QtCore.QSize(90, 90))
        self.checkBox12.setCheckable(True)
        self.checkBox12.setObjectName("checkBox12")
        self.gridLayout_2.addWidget(self.checkBox12, 3, 2, 1, 1)
        self.checkBox20 = QtWidgets.QCheckBox(self.Into_Frame_Item_1)
        self.checkBox20.setText("")
        icon11 = QtGui.QIcon()
        icon11.addPixmap(QtGui.QPixmap("C:\\Albion_Progect\\Albion_Progect\\Pictures/T6_SHOES_CLOTH_SET3@0.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.checkBox20.setIcon(icon11)
        self.checkBox20.setIconSize(QtCore.QSize(90, 90))
        self.checkBox20.setCheckable(True)
        self.checkBox20.setObjectName("checkBox20")
        self.gridLayout_2.addWidget(self.checkBox20, 2, 4, 1, 1)
        self.checkBox16 = QtWidgets.QCheckBox(self.Into_Frame_Item_1)
        self.checkBox16.setText("")
        icon12 = QtGui.QIcon()
        icon12.addPixmap(QtGui.QPixmap("C:\\Albion_Progect\\Albion_Progect\\Pictures/T6_ARMOR_CLOTH_MORGANA.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.checkBox16.setIcon(icon12)
        self.checkBox16.setIconSize(QtCore.QSize(90, 90))
        self.checkBox16.setCheckable(True)
        self.checkBox16.setObjectName("checkBox16")
        self.gridLayout_2.addWidget(self.checkBox16, 7, 2, 1, 1)
        self.checkBox21 = QtWidgets.QCheckBox(self.Into_Frame_Item_1)
        self.checkBox21.setText("")
        icon13 = QtGui.QIcon()
        icon13.addPixmap(QtGui.QPixmap("C:\\Albion_Progect\\Albion_Progect\\Pictures/T6_SHOES_CLOTH_SET2@0.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.checkBox21.setIcon(icon13)
        self.checkBox21.setIconSize(QtCore.QSize(90, 90))
        self.checkBox21.setCheckable(True)
        self.checkBox21.setObjectName("checkBox21")
        self.gridLayout_2.addWidget(self.checkBox21, 3, 4, 1, 1)
        self.checkBox22 = QtWidgets.QCheckBox(self.Into_Frame_Item_1)
        self.checkBox22.setText("")
        icon14 = QtGui.QIcon()
        icon14.addPixmap(QtGui.QPixmap("C:\\Albion_Progect\\Albion_Progect\\Pictures/T6_SHOES_CLOTH_KEEPER@0.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.checkBox22.setIcon(icon14)
        self.checkBox22.setIconSize(QtCore.QSize(90, 90))
        self.checkBox22.setCheckable(True)
        self.checkBox22.setObjectName("checkBox22")
        self.gridLayout_2.addWidget(self.checkBox22, 4, 4, 1, 1)
        self.checkBox27 = QtWidgets.QCheckBox(self.Into_Frame_Item_1)
        self.checkBox27.setText("")
        icon15 = QtGui.QIcon()
        icon15.addPixmap(QtGui.QPixmap("C:\\Albion_Progect\\Albion_Progect\\Pictures/T6_SHOES_CLOTH_FEY@0.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.checkBox27.setIcon(icon15)
        self.checkBox27.setIconSize(QtCore.QSize(90, 90))
        self.checkBox27.setCheckable(True)
        self.checkBox27.setObjectName("checkBox27")
        self.gridLayout_2.addWidget(self.checkBox27, 9, 4, 1, 1)
        self.checkBox5 = QtWidgets.QCheckBox(self.Into_Frame_Item_1)
        self.checkBox5.setText("")
        icon16 = QtGui.QIcon()
        icon16.addPixmap(QtGui.QPixmap("C:\\Albion_Progect\\Albion_Progect\\Pictures/T6_HEAD_CLOTH_ROYAL@0.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.checkBox5.setIcon(icon16)
        self.checkBox5.setIconSize(QtCore.QSize(90, 90))
        self.checkBox5.setCheckable(True)
        self.checkBox5.setObjectName("checkBox5")
        self.gridLayout_2.addWidget(self.checkBox5, 5, 0, 1, 1)
        self.checkBox7 = QtWidgets.QCheckBox(self.Into_Frame_Item_1)
        self.checkBox7.setText("")
        icon17 = QtGui.QIcon()
        icon17.addPixmap(QtGui.QPixmap("C:\\Albion_Progect\\Albion_Progect\\Pictures/T6_HEAD_CLOTH_MORGANA@0.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.checkBox7.setIcon(icon17)
        self.checkBox7.setIconSize(QtCore.QSize(90, 90))
        self.checkBox7.setCheckable(True)
        self.checkBox7.setObjectName("checkBox7")
        self.gridLayout_2.addWidget(self.checkBox7, 7, 0, 1, 1)
        self.checkBox9 = QtWidgets.QCheckBox(self.Into_Frame_Item_1)
        self.checkBox9.setText("")
        icon18 = QtGui.QIcon()
        icon18.addPixmap(QtGui.QPixmap("C:\\Albion_Progect\\Albion_Progect\\Pictures/T6_HEAD_CLOTH_FEY@0.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.checkBox9.setIcon(icon18)
        self.checkBox9.setIconSize(QtCore.QSize(90, 90))
        self.checkBox9.setCheckable(True)
        self.checkBox9.setObjectName("checkBox9")
        self.gridLayout_2.addWidget(self.checkBox9, 9, 0, 1, 1)
        self.checkBox25 = QtWidgets.QCheckBox(self.Into_Frame_Item_1)
        self.checkBox25.setText("")
        icon19 = QtGui.QIcon()
        icon19.addPixmap(QtGui.QPixmap("C:\\Albion_Progect\\Albion_Progect\\Pictures/T6_SHOES_CLOTH_MORGANA@0.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.checkBox25.setIcon(icon19)
        self.checkBox25.setIconSize(QtCore.QSize(90, 90))
        self.checkBox25.setCheckable(True)
        self.checkBox25.setObjectName("checkBox25")
        self.gridLayout_2.addWidget(self.checkBox25, 7, 4, 1, 1)
        self.checkBox6 = QtWidgets.QCheckBox(self.Into_Frame_Item_1)
        self.checkBox6.setText("")
        icon20 = QtGui.QIcon()
        icon20.addPixmap(QtGui.QPixmap("C:\\Albion_Progect\\Albion_Progect\\Pictures/T6_HEAD_CLOTH_HELL@0.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.checkBox6.setIcon(icon20)
        self.checkBox6.setIconSize(QtCore.QSize(90, 90))
        self.checkBox6.setCheckable(True)
        self.checkBox6.setObjectName("checkBox6")
        self.gridLayout_2.addWidget(self.checkBox6, 6, 0, 1, 1)
        self.checkBox4 = QtWidgets.QCheckBox(self.Into_Frame_Item_1)
        self.checkBox4.setText("")
        icon21 = QtGui.QIcon()
        icon21.addPixmap(QtGui.QPixmap("C:\\Albion_Progect\\Albion_Progect\\Pictures/T6_HEAD_CLOTH_KEEPER@0.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.checkBox4.setIcon(icon21)
        self.checkBox4.setIconSize(QtCore.QSize(90, 90))
        self.checkBox4.setCheckable(True)
        self.checkBox4.setObjectName("checkBox4")
        self.gridLayout_2.addWidget(self.checkBox4, 4, 0, 1, 1)
        self.checkBox8 = QtWidgets.QCheckBox(self.Into_Frame_Item_1)
        self.checkBox8.setText("")
        icon22 = QtGui.QIcon()
        icon22.addPixmap(QtGui.QPixmap("C:\\Albion_Progect\\Albion_Progect\\Pictures/T6_HEAD_CLOTH_AVALON@0.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.checkBox8.setIcon(icon22)
        self.checkBox8.setIconSize(QtCore.QSize(90, 90))
        self.checkBox8.setCheckable(True)
        self.checkBox8.setObjectName("checkBox8")
        self.gridLayout_2.addWidget(self.checkBox8, 8, 0, 1, 1)
        self.checkBox3 = QtWidgets.QCheckBox(self.Into_Frame_Item_1)
        self.checkBox3.setText("")
        icon23 = QtGui.QIcon()
        icon23.addPixmap(QtGui.QPixmap("C:\\Albion_Progect\\Albion_Progect\\Pictures/T6_HEAD_CLOTH_SET2@0.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.checkBox3.setIcon(icon23)
        self.checkBox3.setIconSize(QtCore.QSize(90, 90))
        self.checkBox3.setCheckable(True)
        self.checkBox3.setObjectName("checkBox3")
        self.gridLayout_2.addWidget(self.checkBox3, 3, 0, 1, 1)
        self.checkBox2 = QtWidgets.QCheckBox(self.Into_Frame_Item_1)
        self.checkBox2.setText("")
        icon24 = QtGui.QIcon()
        icon24.addPixmap(QtGui.QPixmap("C:\\Albion_Progect\\Albion_Progect\\Pictures/T6_HEAD_CLOTH_SET3@0.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.checkBox2.setIcon(icon24)
        self.checkBox2.setIconSize(QtCore.QSize(90, 90))
        self.checkBox2.setCheckable(True)
        self.checkBox2.setObjectName("checkBox2")
        self.gridLayout_2.addWidget(self.checkBox2, 2, 0, 1, 1)
        self.checkBox24 = QtWidgets.QCheckBox(self.Into_Frame_Item_1)
        self.checkBox24.setText("")
        icon25 = QtGui.QIcon()
        icon25.addPixmap(QtGui.QPixmap("C:\\Albion_Progect\\Albion_Progect\\Pictures/T6_SHOES_CLOTH_HELL@0.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.checkBox24.setIcon(icon25)
        self.checkBox24.setIconSize(QtCore.QSize(90, 90))
        self.checkBox24.setCheckable(True)
        self.checkBox24.setObjectName("checkBox24")
        self.gridLayout_2.addWidget(self.checkBox24, 6, 4, 1, 1)
        self.checkBox26 = QtWidgets.QCheckBox(self.Into_Frame_Item_1)
        self.checkBox26.setText("")
        icon26 = QtGui.QIcon()
        icon26.addPixmap(QtGui.QPixmap("C:\\Albion_Progect\\Albion_Progect\\Pictures/T6_SHOES_CLOTH_AVALON@0.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.checkBox26.setIcon(icon26)
        self.checkBox26.setIconSize(QtCore.QSize(90, 90))
        self.checkBox26.setCheckable(True)
        self.checkBox26.setObjectName("checkBox26")
        self.gridLayout_2.addWidget(self.checkBox26, 8, 4, 1, 1)
        self.Main_Frame_Item.addTab(self.Clotch, "")
        self.Kozaa = QtWidgets.QWidget()
        self.Kozaa.setObjectName("Kozaa")
        self.Into_Frame_Item_2 = QtWidgets.QFrame(self.Kozaa)
        self.Into_Frame_Item_2.setGeometry(QtCore.QRect(5, -3, 460, 800))
        self.Into_Frame_Item_2.setObjectName("Into_Frame_Item_2")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.Into_Frame_Item_2)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.checkBox32 = QtWidgets.QCheckBox(self.Into_Frame_Item_2)
        self.checkBox32.setText("")
        icon27 = QtGui.QIcon()
        icon27.addPixmap(QtGui.QPixmap("C:\\Albion_Progect\\Albion_Progect\\Pictures/T6_HEAD_LEATHER_ROYAL@0.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.checkBox32.setIcon(icon27)
        self.checkBox32.setIconSize(QtCore.QSize(90, 90))
        self.checkBox32.setCheckable(True)
        self.checkBox32.setObjectName("checkBox32")
        self.gridLayout_3.addWidget(self.checkBox32, 4, 0, 1, 1)
        self.checkBox51 = QtWidgets.QCheckBox(self.Into_Frame_Item_2)
        self.checkBox51.setText("")
        icon28 = QtGui.QIcon()
        icon28.addPixmap(QtGui.QPixmap("C:\\Albion_Progect\\Albion_Progect\\Pictures/T6_SHOES_LEATHER_HELL@0.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.checkBox51.setIcon(icon28)
        self.checkBox51.setIconSize(QtCore.QSize(90, 90))
        self.checkBox51.setCheckable(True)
        self.checkBox51.setObjectName("checkBox51")
        self.gridLayout_3.addWidget(self.checkBox51, 5, 2, 1, 1)
        self.checkBox35 = QtWidgets.QCheckBox(self.Into_Frame_Item_2)
        self.checkBox35.setText("")
        icon29 = QtGui.QIcon()
        icon29.addPixmap(QtGui.QPixmap("C:\\Albion_Progect\\Albion_Progect\\Pictures/T6_HEAD_LEATHER_AVALON@0.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.checkBox35.setIcon(icon29)
        self.checkBox35.setIconSize(QtCore.QSize(90, 90))
        self.checkBox35.setCheckable(True)
        self.checkBox35.setObjectName("checkBox35")
        self.gridLayout_3.addWidget(self.checkBox35, 7, 0, 1, 1)
        self.checkBox54 = QtWidgets.QCheckBox(self.Into_Frame_Item_2)
        self.checkBox54.setText("")
        icon30 = QtGui.QIcon()
        icon30.addPixmap(QtGui.QPixmap("C:\\Albion_Progect\\Albion_Progect\\Pictures/T6_SHOES_LEATHER_FEY@0.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.checkBox54.setIcon(icon30)
        self.checkBox54.setIconSize(QtCore.QSize(90, 90))
        self.checkBox54.setCheckable(True)
        self.checkBox54.setObjectName("checkBox54")
        self.gridLayout_3.addWidget(self.checkBox54, 8, 2, 1, 1)
        self.checkBox50 = QtWidgets.QCheckBox(self.Into_Frame_Item_2)
        self.checkBox50.setText("")
        icon31 = QtGui.QIcon()
        icon31.addPixmap(QtGui.QPixmap("C:\\Albion_Progect\\Albion_Progect\\Pictures/T6_SHOES_LEATHER_ROYAL@0.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.checkBox50.setIcon(icon31)
        self.checkBox50.setIconSize(QtCore.QSize(90, 90))
        self.checkBox50.setCheckable(True)
        self.checkBox50.setObjectName("checkBox50")
        self.gridLayout_3.addWidget(self.checkBox50, 4, 2, 1, 1)
        self.checkBox49 = QtWidgets.QCheckBox(self.Into_Frame_Item_2)
        self.checkBox49.setText("")
        icon32 = QtGui.QIcon()
        icon32.addPixmap(QtGui.QPixmap("C:\\Albion_Progect\\Albion_Progect\\Pictures/T6_SHOES_LEATHER_MORGANA@0.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.checkBox49.setIcon(icon32)
        self.checkBox49.setIconSize(QtCore.QSize(90, 90))
        self.checkBox49.setCheckable(True)
        self.checkBox49.setObjectName("checkBox49")
        self.gridLayout_3.addWidget(self.checkBox49, 3, 2, 1, 1)
        self.checkBox28 = QtWidgets.QCheckBox(self.Into_Frame_Item_2)
        self.checkBox28.setText("")
        icon33 = QtGui.QIcon()
        icon33.addPixmap(QtGui.QPixmap("C:\\Albion_Progect\\Albion_Progect\\Pictures/T6_HEAD_LEATHER_SET1@0.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.checkBox28.setIcon(icon33)
        self.checkBox28.setIconSize(QtCore.QSize(90, 90))
        self.checkBox28.setCheckable(True)
        self.checkBox28.setObjectName("checkBox28")
        self.gridLayout_3.addWidget(self.checkBox28, 0, 0, 1, 1)
        self.checkBox46 = QtWidgets.QCheckBox(self.Into_Frame_Item_2)
        self.checkBox46.setText("")
        icon34 = QtGui.QIcon()
        icon34.addPixmap(QtGui.QPixmap("C:\\Albion_Progect\\Albion_Progect\\Pictures/T6_SHOES_LEATHER_SET1@0.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.checkBox46.setIcon(icon34)
        self.checkBox46.setIconSize(QtCore.QSize(90, 90))
        self.checkBox46.setCheckable(True)
        self.checkBox46.setObjectName("checkBox46")
        self.gridLayout_3.addWidget(self.checkBox46, 0, 2, 1, 1)
        self.checkBox53 = QtWidgets.QCheckBox(self.Into_Frame_Item_2)
        self.checkBox53.setText("")
        icon35 = QtGui.QIcon()
        icon35.addPixmap(QtGui.QPixmap("C:\\Albion_Progect\\Albion_Progect\\Pictures/T6_SHOES_LEATHER_AVALON@0.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.checkBox53.setIcon(icon35)
        self.checkBox53.setIconSize(QtCore.QSize(90, 90))
        self.checkBox53.setCheckable(True)
        self.checkBox53.setObjectName("checkBox53")
        self.gridLayout_3.addWidget(self.checkBox53, 7, 2, 1, 1)
        self.checkBox37 = QtWidgets.QCheckBox(self.Into_Frame_Item_2)
        self.checkBox37.setText("")
        icon36 = QtGui.QIcon()
        icon36.addPixmap(QtGui.QPixmap("C:\\Albion_Progect\\Albion_Progect\\Pictures/T6_ARMOR_LEATHER_SET1@0.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.checkBox37.setIcon(icon36)
        self.checkBox37.setIconSize(QtCore.QSize(90, 90))
        self.checkBox37.setCheckable(True)
        self.checkBox37.setObjectName("checkBox37")
        self.gridLayout_3.addWidget(self.checkBox37, 0, 1, 1, 1)
        self.checkBox29 = QtWidgets.QCheckBox(self.Into_Frame_Item_2)
        self.checkBox29.setText("")
        icon37 = QtGui.QIcon()
        icon37.addPixmap(QtGui.QPixmap("C:\\Albion_Progect\\Albion_Progect\\Pictures/T6_HEAD_LEATHER_SET2@0.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.checkBox29.setIcon(icon37)
        self.checkBox29.setIconSize(QtCore.QSize(90, 90))
        self.checkBox29.setCheckable(True)
        self.checkBox29.setObjectName("checkBox29")
        self.gridLayout_3.addWidget(self.checkBox29, 1, 0, 1, 1)
        self.checkBox39 = QtWidgets.QCheckBox(self.Into_Frame_Item_2)
        self.checkBox39.setText("")
        icon38 = QtGui.QIcon()
        icon38.addPixmap(QtGui.QPixmap("C:\\Albion_Progect\\Albion_Progect\\Pictures/T6_ARMOR_LEATHER_SET3@0.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.checkBox39.setIcon(icon38)
        self.checkBox39.setIconSize(QtCore.QSize(90, 90))
        self.checkBox39.setCheckable(True)
        self.checkBox39.setObjectName("checkBox39")
        self.gridLayout_3.addWidget(self.checkBox39, 2, 1, 1, 1)
        self.checkBox36 = QtWidgets.QCheckBox(self.Into_Frame_Item_2)
        self.checkBox36.setText("")
        icon39 = QtGui.QIcon()
        icon39.addPixmap(QtGui.QPixmap("C:\\Albion_Progect\\Albion_Progect\\Pictures/T6_HEAD_LEATHER_FEY@0.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.checkBox36.setIcon(icon39)
        self.checkBox36.setIconSize(QtCore.QSize(90, 90))
        self.checkBox36.setCheckable(True)
        self.checkBox36.setObjectName("checkBox36")
        self.gridLayout_3.addWidget(self.checkBox36, 8, 0, 1, 1)
        self.checkBox38 = QtWidgets.QCheckBox(self.Into_Frame_Item_2)
        self.checkBox38.setText("")
        icon40 = QtGui.QIcon()
        icon40.addPixmap(QtGui.QPixmap("C:\\Albion_Progect\\Albion_Progect\\Pictures/T6_ARMOR_LEATHER_SET2@0.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.checkBox38.setIcon(icon40)
        self.checkBox38.setIconSize(QtCore.QSize(90, 90))
        self.checkBox38.setCheckable(True)
        self.checkBox38.setObjectName("checkBox38")
        self.gridLayout_3.addWidget(self.checkBox38, 1, 1, 1, 1)
        self.checkBox40 = QtWidgets.QCheckBox(self.Into_Frame_Item_2)
        self.checkBox40.setText("")
        icon41 = QtGui.QIcon()
        icon41.addPixmap(QtGui.QPixmap("C:\\Albion_Progect\\Albion_Progect\\Pictures/T6_ARMOR_LEATHER_MORGANA@0.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.checkBox40.setIcon(icon41)
        self.checkBox40.setIconSize(QtCore.QSize(90, 90))
        self.checkBox40.setCheckable(True)
        self.checkBox40.setObjectName("checkBox40")
        self.gridLayout_3.addWidget(self.checkBox40, 3, 1, 1, 1)
        self.checkBox41 = QtWidgets.QCheckBox(self.Into_Frame_Item_2)
        self.checkBox41.setText("")
        icon42 = QtGui.QIcon()
        icon42.addPixmap(QtGui.QPixmap("C:\\Albion_Progect\\Albion_Progect\\Pictures/T6_ARMOR_LEATHER_ROYAL@0.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.checkBox41.setIcon(icon42)
        self.checkBox41.setIconSize(QtCore.QSize(90, 90))
        self.checkBox41.setCheckable(True)
        self.checkBox41.setObjectName("checkBox41")
        self.gridLayout_3.addWidget(self.checkBox41, 4, 1, 1, 1)
        self.checkBox42 = QtWidgets.QCheckBox(self.Into_Frame_Item_2)
        self.checkBox42.setText("")
        icon43 = QtGui.QIcon()
        icon43.addPixmap(QtGui.QPixmap("C:\\Albion_Progect\\Albion_Progect\\Pictures/T6_ARMOR_LEATHER_HELL@0.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.checkBox42.setIcon(icon43)
        self.checkBox42.setIconSize(QtCore.QSize(90, 90))
        self.checkBox42.setCheckable(True)
        self.checkBox42.setObjectName("checkBox42")
        self.gridLayout_3.addWidget(self.checkBox42, 5, 1, 1, 1)
        self.checkBox45 = QtWidgets.QCheckBox(self.Into_Frame_Item_2)
        self.checkBox45.setText("")
        icon44 = QtGui.QIcon()
        icon44.addPixmap(QtGui.QPixmap("C:\\Albion_Progect\\Albion_Progect\\Pictures/T6_ARMOR_LEATHER_FEY@0.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.checkBox45.setIcon(icon44)
        self.checkBox45.setIconSize(QtCore.QSize(90, 90))
        self.checkBox45.setCheckable(True)
        self.checkBox45.setObjectName("checkBox45")
        self.gridLayout_3.addWidget(self.checkBox45, 8, 1, 1, 1)
        self.checkBox47 = QtWidgets.QCheckBox(self.Into_Frame_Item_2)
        self.checkBox47.setText("")
        icon45 = QtGui.QIcon()
        icon45.addPixmap(QtGui.QPixmap("C:\\Albion_Progect\\Albion_Progect\\Pictures/T6_SHOES_LEATHER_SET2@0.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.checkBox47.setIcon(icon45)
        self.checkBox47.setIconSize(QtCore.QSize(90, 90))
        self.checkBox47.setCheckable(True)
        self.checkBox47.setObjectName("checkBox47")
        self.gridLayout_3.addWidget(self.checkBox47, 1, 2, 1, 1)
        self.checkBox43 = QtWidgets.QCheckBox(self.Into_Frame_Item_2)
        self.checkBox43.setText("")
        icon46 = QtGui.QIcon()
        icon46.addPixmap(QtGui.QPixmap("C:\\Albion_Progect\\Albion_Progect\\Pictures/T6_ARMOR_LEATHER_UNDEAD@0.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.checkBox43.setIcon(icon46)
        self.checkBox43.setIconSize(QtCore.QSize(90, 90))
        self.checkBox43.setCheckable(True)
        self.checkBox43.setObjectName("checkBox43")
        self.gridLayout_3.addWidget(self.checkBox43, 6, 1, 1, 1)
        self.checkBox44 = QtWidgets.QCheckBox(self.Into_Frame_Item_2)
        self.checkBox44.setText("")
        icon47 = QtGui.QIcon()
        icon47.addPixmap(QtGui.QPixmap("C:\\Albion_Progect\\Albion_Progect\\Pictures/T6_ARMOR_LEATHER_AVALON@0.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.checkBox44.setIcon(icon47)
        self.checkBox44.setIconSize(QtCore.QSize(90, 90))
        self.checkBox44.setCheckable(True)
        self.checkBox44.setObjectName("checkBox44")
        self.gridLayout_3.addWidget(self.checkBox44, 7, 1, 1, 1)
        self.checkBox34 = QtWidgets.QCheckBox(self.Into_Frame_Item_2)
        self.checkBox34.setText("")
        icon48 = QtGui.QIcon()
        icon48.addPixmap(QtGui.QPixmap("C:\\Albion_Progect\\Albion_Progect\\Pictures/T6_HEAD_LEATHER_UNDEAD@0.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.checkBox34.setIcon(icon48)
        self.checkBox34.setIconSize(QtCore.QSize(90, 90))
        self.checkBox34.setCheckable(True)
        self.checkBox34.setObjectName("checkBox34")
        self.gridLayout_3.addWidget(self.checkBox34, 6, 0, 1, 1)
        self.checkBox33 = QtWidgets.QCheckBox(self.Into_Frame_Item_2)
        self.checkBox33.setText("")
        icon49 = QtGui.QIcon()
        icon49.addPixmap(QtGui.QPixmap("C:\\Albion_Progect\\Albion_Progect\\Pictures/T6_HEAD_LEATHER_HELL@0.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.checkBox33.setIcon(icon49)
        self.checkBox33.setIconSize(QtCore.QSize(90, 90))
        self.checkBox33.setCheckable(True)
        self.checkBox33.setObjectName("checkBox33")
        self.gridLayout_3.addWidget(self.checkBox33, 5, 0, 1, 1)
        self.checkBox31 = QtWidgets.QCheckBox(self.Into_Frame_Item_2)
        self.checkBox31.setText("")
        icon50 = QtGui.QIcon()
        icon50.addPixmap(QtGui.QPixmap("C:\\Albion_Progect\\Albion_Progect\\Pictures/T6_HEAD_LEATHER_MORGANA@0.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.checkBox31.setIcon(icon50)
        self.checkBox31.setIconSize(QtCore.QSize(90, 90))
        self.checkBox31.setCheckable(True)
        self.checkBox31.setObjectName("checkBox31")
        self.gridLayout_3.addWidget(self.checkBox31, 3, 0, 1, 1)
        self.checkBox30 = QtWidgets.QCheckBox(self.Into_Frame_Item_2)
        self.checkBox30.setText("")
        icon51 = QtGui.QIcon()
        icon51.addPixmap(QtGui.QPixmap("C:\\Albion_Progect\\Albion_Progect\\Pictures/T6_HEAD_LEATHER_SET3@0.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.checkBox30.setIcon(icon51)
        self.checkBox30.setIconSize(QtCore.QSize(90, 90))
        self.checkBox30.setCheckable(True)
        self.checkBox30.setObjectName("checkBox30")
        self.gridLayout_3.addWidget(self.checkBox30, 2, 0, 1, 1)
        self.checkBox48 = QtWidgets.QCheckBox(self.Into_Frame_Item_2)
        self.checkBox48.setText("")
        icon52 = QtGui.QIcon()
        icon52.addPixmap(QtGui.QPixmap("C:\\Albion_Progect\\Albion_Progect\\Pictures/T6_SHOES_LEATHER_SET3@0.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.checkBox48.setIcon(icon52)
        self.checkBox48.setIconSize(QtCore.QSize(90, 90))
        self.checkBox48.setCheckable(True)
        self.checkBox48.setObjectName("checkBox48")
        self.gridLayout_3.addWidget(self.checkBox48, 2, 2, 1, 1)
        self.checkBox52 = QtWidgets.QCheckBox(self.Into_Frame_Item_2)
        self.checkBox52.setText("")
        icon53 = QtGui.QIcon()
        icon53.addPixmap(QtGui.QPixmap("C:\\Albion_Progect\\Albion_Progect\\Pictures/T6_SHOES_LEATHER_UNDEAD@0.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.checkBox52.setIcon(icon53)
        self.checkBox52.setIconSize(QtCore.QSize(90, 90))
        self.checkBox52.setCheckable(True)
        self.checkBox52.setObjectName("checkBox52")
        self.gridLayout_3.addWidget(self.checkBox52, 6, 2, 1, 1)
        self.Main_Frame_Item.addTab(self.Kozaa, "")
        self.Lat = QtWidgets.QWidget()
        self.Lat.setObjectName("Lat")
        self.Into_Frame_Item_3 = QtWidgets.QFrame(self.Lat)
        self.Into_Frame_Item_3.setGeometry(QtCore.QRect(5, -3, 460, 800))
        self.Into_Frame_Item_3.setObjectName("Into_Frame_Item_3")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.Into_Frame_Item_3)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.checkBox78 = QtWidgets.QCheckBox(self.Into_Frame_Item_3)
        self.checkBox78.setText("")
        icon54 = QtGui.QIcon()
        icon54.addPixmap(QtGui.QPixmap("C:\\Albion_Progect\\Albion_Progect\\Pictures/T6_SHOES_PLATE_HELL@0.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.checkBox78.setIcon(icon54)
        self.checkBox78.setIconSize(QtCore.QSize(90, 90))
        self.checkBox78.setCheckable(True)
        self.checkBox78.setObjectName("checkBox78")
        self.gridLayout_4.addWidget(self.checkBox78, 5, 2, 1, 1)
        self.checkBox79 = QtWidgets.QCheckBox(self.Into_Frame_Item_3)
        self.checkBox79.setText("")
        icon55 = QtGui.QIcon()
        icon55.addPixmap(QtGui.QPixmap("C:\\Albion_Progect\\Albion_Progect\\Pictures/T6_SHOES_PLATE_KEEPER@0.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.checkBox79.setIcon(icon55)
        self.checkBox79.setIconSize(QtCore.QSize(90, 90))
        self.checkBox79.setCheckable(True)
        self.checkBox79.setObjectName("checkBox79")
        self.gridLayout_4.addWidget(self.checkBox79, 6, 2, 1, 1)
        self.checkBox75 = QtWidgets.QCheckBox(self.Into_Frame_Item_3)
        self.checkBox75.setText("")
        icon56 = QtGui.QIcon()
        icon56.addPixmap(QtGui.QPixmap("C:\\Albion_Progect\\Albion_Progect\\Pictures/T6_SHOES_PLATE_SET3@0.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.checkBox75.setIcon(icon56)
        self.checkBox75.setIconSize(QtCore.QSize(90, 90))
        self.checkBox75.setCheckable(True)
        self.checkBox75.setObjectName("checkBox75")
        self.gridLayout_4.addWidget(self.checkBox75, 2, 2, 1, 1)
        self.checkBox76 = QtWidgets.QCheckBox(self.Into_Frame_Item_3)
        self.checkBox76.setText("")
        icon57 = QtGui.QIcon()
        icon57.addPixmap(QtGui.QPixmap("C:\\Albion_Progect\\Albion_Progect\\Pictures/T6_SHOES_PLATE_UNDEAD@0.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.checkBox76.setIcon(icon57)
        self.checkBox76.setIconSize(QtCore.QSize(90, 90))
        self.checkBox76.setCheckable(True)
        self.checkBox76.setObjectName("checkBox76")
        self.gridLayout_4.addWidget(self.checkBox76, 3, 2, 1, 1)
        self.checkBox64 = QtWidgets.QCheckBox(self.Into_Frame_Item_3)
        self.checkBox64.setText("")
        icon58 = QtGui.QIcon()
        icon58.addPixmap(QtGui.QPixmap("C:\\Albion_Progect\\Albion_Progect\\Pictures/T6_ARMOR_PLATE_SET1@0.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.checkBox64.setIcon(icon58)
        self.checkBox64.setIconSize(QtCore.QSize(90, 90))
        self.checkBox64.setCheckable(True)
        self.checkBox64.setObjectName("checkBox64")
        self.gridLayout_4.addWidget(self.checkBox64, 0, 1, 1, 1)
        self.checkBox77 = QtWidgets.QCheckBox(self.Into_Frame_Item_3)
        self.checkBox77.setText("")
        icon59 = QtGui.QIcon()
        icon59.addPixmap(QtGui.QPixmap("C:\\Albion_Progect\\Albion_Progect\\Pictures/T6_SHOES_PLATE_ROYAL@0.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.checkBox77.setIcon(icon59)
        self.checkBox77.setIconSize(QtCore.QSize(90, 90))
        self.checkBox77.setCheckable(True)
        self.checkBox77.setObjectName("checkBox77")
        self.gridLayout_4.addWidget(self.checkBox77, 4, 2, 1, 1)
        self.checkBox67 = QtWidgets.QCheckBox(self.Into_Frame_Item_3)
        self.checkBox67.setText("")
        icon60 = QtGui.QIcon()
        icon60.addPixmap(QtGui.QPixmap("C:\\Albion_Progect\\Albion_Progect\\Pictures/T6_ARMOR_PLATE_UNDEAD@0.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.checkBox67.setIcon(icon60)
        self.checkBox67.setIconSize(QtCore.QSize(90, 90))
        self.checkBox67.setCheckable(True)
        self.checkBox67.setObjectName("checkBox67")
        self.gridLayout_4.addWidget(self.checkBox67, 3, 1, 1, 1)
        self.checkBox57 = QtWidgets.QCheckBox(self.Into_Frame_Item_3)
        self.checkBox57.setText("")
        icon61 = QtGui.QIcon()
        icon61.addPixmap(QtGui.QPixmap("C:\\Albion_Progect\\Albion_Progect\\Pictures/T6_HEAD_PLATE_SET3@0.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.checkBox57.setIcon(icon61)
        self.checkBox57.setIconSize(QtCore.QSize(90, 90))
        self.checkBox57.setCheckable(True)
        self.checkBox57.setObjectName("checkBox57")
        self.gridLayout_4.addWidget(self.checkBox57, 2, 0, 1, 1)
        self.checkBox55 = QtWidgets.QCheckBox(self.Into_Frame_Item_3)
        self.checkBox55.setText("")
        icon62 = QtGui.QIcon()
        icon62.addPixmap(QtGui.QPixmap("C:\\Albion_Progect\\Albion_Progect\\Pictures/T6_HEAD_PLATE_SET1@0.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.checkBox55.setIcon(icon62)
        self.checkBox55.setIconSize(QtCore.QSize(90, 90))
        self.checkBox55.setCheckable(True)
        self.checkBox55.setObjectName("checkBox55")
        self.gridLayout_4.addWidget(self.checkBox55, 0, 0, 1, 1)
        self.checkBox73 = QtWidgets.QCheckBox(self.Into_Frame_Item_3)
        self.checkBox73.setText("")
        icon63 = QtGui.QIcon()
        icon63.addPixmap(QtGui.QPixmap("C:\\Albion_Progect\\Albion_Progect\\Pictures/T6_SHOES_PLATE_SET1@0.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.checkBox73.setIcon(icon63)
        self.checkBox73.setIconSize(QtCore.QSize(90, 90))
        self.checkBox73.setCheckable(True)
        self.checkBox73.setObjectName("checkBox73")
        self.gridLayout_4.addWidget(self.checkBox73, 0, 2, 1, 1)
        self.checkBox56 = QtWidgets.QCheckBox(self.Into_Frame_Item_3)
        self.checkBox56.setText("")
        icon64 = QtGui.QIcon()
        icon64.addPixmap(QtGui.QPixmap("C:\\Albion_Progect\\Albion_Progect\\Pictures/T6_HEAD_PLATE_SET2@0.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.checkBox56.setIcon(icon64)
        self.checkBox56.setIconSize(QtCore.QSize(90, 90))
        self.checkBox56.setCheckable(True)
        self.checkBox56.setObjectName("checkBox56")
        self.gridLayout_4.addWidget(self.checkBox56, 1, 0, 1, 1)
        self.checkBox65 = QtWidgets.QCheckBox(self.Into_Frame_Item_3)
        self.checkBox65.setText("")
        icon65 = QtGui.QIcon()
        icon65.addPixmap(QtGui.QPixmap("C:\\Albion_Progect\\Albion_Progect\\Pictures/T6_ARMOR_PLATE_SET2@0.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.checkBox65.setIcon(icon65)
        self.checkBox65.setIconSize(QtCore.QSize(90, 90))
        self.checkBox65.setCheckable(True)
        self.checkBox65.setObjectName("checkBox65")
        self.gridLayout_4.addWidget(self.checkBox65, 1, 1, 1, 1)
        self.checkBox81 = QtWidgets.QCheckBox(self.Into_Frame_Item_3)
        self.checkBox81.setText("")
        icon66 = QtGui.QIcon()
        icon66.addPixmap(QtGui.QPixmap("C:\\Albion_Progect\\Albion_Progect\\Pictures/T6_SHOES_PLATE_FEY@0.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.checkBox81.setIcon(icon66)
        self.checkBox81.setIconSize(QtCore.QSize(90, 90))
        self.checkBox81.setCheckable(True)
        self.checkBox81.setObjectName("checkBox81")
        self.gridLayout_4.addWidget(self.checkBox81, 8, 2, 1, 1)
        self.checkBox70 = QtWidgets.QCheckBox(self.Into_Frame_Item_3)
        self.checkBox70.setText("")
        icon67 = QtGui.QIcon()
        icon67.addPixmap(QtGui.QPixmap("C:\\Albion_Progect\\Albion_Progect\\Pictures/T6_ARMOR_PLATE_KEEPER@0.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.checkBox70.setIcon(icon67)
        self.checkBox70.setIconSize(QtCore.QSize(90, 90))
        self.checkBox70.setCheckable(True)
        self.checkBox70.setObjectName("checkBox70")
        self.gridLayout_4.addWidget(self.checkBox70, 6, 1, 1, 1)
        self.checkBox68 = QtWidgets.QCheckBox(self.Into_Frame_Item_3)
        self.checkBox68.setText("")
        icon68 = QtGui.QIcon()
        icon68.addPixmap(QtGui.QPixmap("C:\\Albion_Progect\\Albion_Progect\\Pictures/T6_ARMOR_PLATE_ROYAL@0.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.checkBox68.setIcon(icon68)
        self.checkBox68.setIconSize(QtCore.QSize(90, 90))
        self.checkBox68.setCheckable(True)
        self.checkBox68.setObjectName("checkBox68")
        self.gridLayout_4.addWidget(self.checkBox68, 4, 1, 1, 1)
        self.checkBox66 = QtWidgets.QCheckBox(self.Into_Frame_Item_3)
        self.checkBox66.setText("")
        icon69 = QtGui.QIcon()
        icon69.addPixmap(QtGui.QPixmap("C:\\Albion_Progect\\Albion_Progect\\Pictures/T6_ARMOR_PLATE_SET3@0.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.checkBox66.setIcon(icon69)
        self.checkBox66.setIconSize(QtCore.QSize(90, 90))
        self.checkBox66.setCheckable(True)
        self.checkBox66.setObjectName("checkBox66")
        self.gridLayout_4.addWidget(self.checkBox66, 2, 1, 1, 1)
        self.checkBox69 = QtWidgets.QCheckBox(self.Into_Frame_Item_3)
        self.checkBox69.setText("")
        icon70 = QtGui.QIcon()
        icon70.addPixmap(QtGui.QPixmap("C:\\Albion_Progect\\Albion_Progect\\Pictures/T6_ARMOR_PLATE_HELL@0.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.checkBox69.setIcon(icon70)
        self.checkBox69.setIconSize(QtCore.QSize(90, 90))
        self.checkBox69.setCheckable(True)
        self.checkBox69.setObjectName("checkBox69")
        self.gridLayout_4.addWidget(self.checkBox69, 5, 1, 1, 1)
        self.checkBox80 = QtWidgets.QCheckBox(self.Into_Frame_Item_3)
        self.checkBox80.setText("")
        icon71 = QtGui.QIcon()
        icon71.addPixmap(QtGui.QPixmap("C:\\Albion_Progect\\Albion_Progect\\Pictures/T6_SHOES_PLATE_AVALON@0.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.checkBox80.setIcon(icon71)
        self.checkBox80.setIconSize(QtCore.QSize(90, 90))
        self.checkBox80.setCheckable(True)
        self.checkBox80.setObjectName("checkBox80")
        self.gridLayout_4.addWidget(self.checkBox80, 7, 2, 1, 1)
        self.checkBox74 = QtWidgets.QCheckBox(self.Into_Frame_Item_3)
        self.checkBox74.setText("")
        icon72 = QtGui.QIcon()
        icon72.addPixmap(QtGui.QPixmap("C:\\Albion_Progect\\Albion_Progect\\Pictures/T6_SHOES_PLATE_SET2@0.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.checkBox74.setIcon(icon72)
        self.checkBox74.setIconSize(QtCore.QSize(90, 90))
        self.checkBox74.setCheckable(True)
        self.checkBox74.setObjectName("checkBox74")
        self.gridLayout_4.addWidget(self.checkBox74, 1, 2, 1, 1)
        self.checkBox62 = QtWidgets.QCheckBox(self.Into_Frame_Item_3)
        self.checkBox62.setText("")
        icon73 = QtGui.QIcon()
        icon73.addPixmap(QtGui.QPixmap("C:\\Albion_Progect\\Albion_Progect\\Pictures/T6_HEAD_PLATE_AVALON@0.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.checkBox62.setIcon(icon73)
        self.checkBox62.setIconSize(QtCore.QSize(90, 90))
        self.checkBox62.setCheckable(True)
        self.checkBox62.setObjectName("checkBox62")
        self.gridLayout_4.addWidget(self.checkBox62, 7, 0, 1, 1)
        self.checkBox71 = QtWidgets.QCheckBox(self.Into_Frame_Item_3)
        self.checkBox71.setText("")
        icon74 = QtGui.QIcon()
        icon74.addPixmap(QtGui.QPixmap("C:\\Albion_Progect\\Albion_Progect\\Pictures/T6_ARMOR_PLATE_AVALON@0.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.checkBox71.setIcon(icon74)
        self.checkBox71.setIconSize(QtCore.QSize(90, 90))
        self.checkBox71.setCheckable(True)
        self.checkBox71.setObjectName("checkBox71")
        self.gridLayout_4.addWidget(self.checkBox71, 7, 1, 1, 1)
        self.checkBox72 = QtWidgets.QCheckBox(self.Into_Frame_Item_3)
        self.checkBox72.setText("")
        icon75 = QtGui.QIcon()
        icon75.addPixmap(QtGui.QPixmap("C:\\Albion_Progect\\Albion_Progect\\Pictures/T6_ARMOR_PLATE_FEY@0.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.checkBox72.setIcon(icon75)
        self.checkBox72.setIconSize(QtCore.QSize(90, 90))
        self.checkBox72.setCheckable(True)
        self.checkBox72.setObjectName("checkBox72")
        self.gridLayout_4.addWidget(self.checkBox72, 8, 1, 1, 1)
        self.checkBox59 = QtWidgets.QCheckBox(self.Into_Frame_Item_3)
        self.checkBox59.setText("")
        icon76 = QtGui.QIcon()
        icon76.addPixmap(QtGui.QPixmap("C:\\Albion_Progect\\Albion_Progect\\Pictures/T6_HEAD_PLATE_ROYAL@0.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.checkBox59.setIcon(icon76)
        self.checkBox59.setIconSize(QtCore.QSize(90, 90))
        self.checkBox59.setCheckable(True)
        self.checkBox59.setObjectName("checkBox59")
        self.gridLayout_4.addWidget(self.checkBox59, 4, 0, 1, 1)
        self.checkBox60 = QtWidgets.QCheckBox(self.Into_Frame_Item_3)
        self.checkBox60.setText("")
        icon77 = QtGui.QIcon()
        icon77.addPixmap(QtGui.QPixmap("C:\\Albion_Progect\\Albion_Progect\\Pictures/T6_HEAD_PLATE_HELL@0.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.checkBox60.setIcon(icon77)
        self.checkBox60.setIconSize(QtCore.QSize(90, 90))
        self.checkBox60.setCheckable(True)
        self.checkBox60.setObjectName("checkBox60")
        self.gridLayout_4.addWidget(self.checkBox60, 5, 0, 1, 1)
        self.checkBox63 = QtWidgets.QCheckBox(self.Into_Frame_Item_3)
        self.checkBox63.setText("")
        icon78 = QtGui.QIcon()
        icon78.addPixmap(QtGui.QPixmap("C:\\Albion_Progect\\Albion_Progect\\Pictures/T6_HEAD_PLATE_FEY@0.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.checkBox63.setIcon(icon78)
        self.checkBox63.setIconSize(QtCore.QSize(90, 90))
        self.checkBox63.setCheckable(True)
        self.checkBox63.setObjectName("checkBox63")
        self.gridLayout_4.addWidget(self.checkBox63, 8, 0, 1, 1)
        self.checkBox58 = QtWidgets.QCheckBox(self.Into_Frame_Item_3)
        self.checkBox58.setText("")
        icon79 = QtGui.QIcon()
        icon79.addPixmap(QtGui.QPixmap("C:\\Albion_Progect\\Albion_Progect\\Pictures/T6_HEAD_PLATE_UNDEAD@0.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.checkBox58.setIcon(icon79)
        self.checkBox58.setIconSize(QtCore.QSize(90, 90))
        self.checkBox58.setCheckable(True)
        self.checkBox58.setObjectName("checkBox58")
        self.gridLayout_4.addWidget(self.checkBox58, 3, 0, 1, 1)
        self.checkBox61 = QtWidgets.QCheckBox(self.Into_Frame_Item_3)
        self.checkBox61.setText("")
        icon80 = QtGui.QIcon()
        icon80.addPixmap(QtGui.QPixmap("C:\\Albion_Progect\\Albion_Progect\\Pictures/T6_HEAD_PLATE_KEEPER@0.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.checkBox61.setIcon(icon80)
        self.checkBox61.setIconSize(QtCore.QSize(90, 90))
        self.checkBox61.setCheckable(True)
        self.checkBox61.setObjectName("checkBox61")
        self.gridLayout_4.addWidget(self.checkBox61, 6, 0, 1, 1)
        self.Main_Frame_Item.addTab(self.Lat, "")
        self.Bags = QtWidgets.QWidget()
        self.Bags.setObjectName("Bags")
        self.Into_Frame_Item_5 = QtWidgets.QFrame(self.Bags)
        self.Into_Frame_Item_5.setGeometry(QtCore.QRect(0, 0, 420, 780))
        self.Into_Frame_Item_5.setObjectName("Into_Frame_Item_5")
        self.gridLayout_7 = QtWidgets.QGridLayout(self.Into_Frame_Item_5)
        self.gridLayout_7.setObjectName("gridLayout_7")
        self.CheckBox_Things_6 = QtWidgets.QCheckBox(self.Into_Frame_Item_5)
        font = QtGui.QFont()
        font.setPointSize(8)
        self.CheckBox_Things_6.setFont(font)
        self.CheckBox_Things_6.setText("")
        icon81 = QtGui.QIcon()
        icon81.addPixmap(QtGui.QPixmap("C:\\Albion_Progect\\Albion_Progect\\Pictures/Master\'s Morgana Cape.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.CheckBox_Things_6.setIcon(icon81)
        self.CheckBox_Things_6.setIconSize(QtCore.QSize(95, 95))
        self.CheckBox_Things_6.setCheckable(True)
        self.CheckBox_Things_6.setObjectName("CheckBox_Things_6")
        self.gridLayout_7.addWidget(self.CheckBox_Things_6, 3, 2, 1, 1)
        self.CheckBox_Things_7 = QtWidgets.QCheckBox(self.Into_Frame_Item_5)
        font = QtGui.QFont()
        font.setPointSize(8)
        self.CheckBox_Things_7.setFont(font)
        self.CheckBox_Things_7.setText("")
        icon82 = QtGui.QIcon()
        icon82.addPixmap(QtGui.QPixmap("C:\\Albion_Progect\\Albion_Progect\\Pictures/Master\'s Demon Cape.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.CheckBox_Things_7.setIcon(icon82)
        self.CheckBox_Things_7.setIconSize(QtCore.QSize(95, 95))
        self.CheckBox_Things_7.setCheckable(True)
        self.CheckBox_Things_7.setObjectName("CheckBox_Things_7")
        self.gridLayout_7.addWidget(self.CheckBox_Things_7, 4, 0, 1, 1)
        self.CheckBox_Things_8 = QtWidgets.QCheckBox(self.Into_Frame_Item_5)
        font = QtGui.QFont()
        font.setPointSize(8)
        self.CheckBox_Things_8.setFont(font)
        self.CheckBox_Things_8.setText("")
        icon83 = QtGui.QIcon()
        icon83.addPixmap(QtGui.QPixmap("C:\\Albion_Progect\\Albion_Progect\\Pictures/Master\'s Undead Cape.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.CheckBox_Things_8.setIcon(icon83)
        self.CheckBox_Things_8.setIconSize(QtCore.QSize(95, 95))
        self.CheckBox_Things_8.setCheckable(True)
        self.CheckBox_Things_8.setObjectName("CheckBox_Things_8")
        self.gridLayout_7.addWidget(self.CheckBox_Things_8, 4, 1, 1, 1)
        self.CheckBox_Things_5 = QtWidgets.QCheckBox(self.Into_Frame_Item_5)
        font = QtGui.QFont()
        font.setPointSize(8)
        self.CheckBox_Things_5.setFont(font)
        self.CheckBox_Things_5.setText("")
        icon84 = QtGui.QIcon()
        icon84.addPixmap(QtGui.QPixmap("C:\\Albion_Progect\\Albion_Progect\\Pictures/Master\'s Keeper Cape.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.CheckBox_Things_5.setIcon(icon84)
        self.CheckBox_Things_5.setIconSize(QtCore.QSize(95, 95))
        self.CheckBox_Things_5.setCheckable(True)
        self.CheckBox_Things_5.setObjectName("CheckBox_Things_5")
        self.gridLayout_7.addWidget(self.CheckBox_Things_5, 3, 1, 1, 1)
        self.CheckBox_Things_9 = QtWidgets.QCheckBox(self.Into_Frame_Item_5)
        font = QtGui.QFont()
        font.setPointSize(8)
        self.CheckBox_Things_9.setFont(font)
        self.CheckBox_Things_9.setText("")
        icon85 = QtGui.QIcon()
        icon85.addPixmap(QtGui.QPixmap("C:\\Albion_Progect\\Albion_Progect\\Pictures/Master\'s Caerleon Cape.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.CheckBox_Things_9.setIcon(icon85)
        self.CheckBox_Things_9.setIconSize(QtCore.QSize(95, 95))
        self.CheckBox_Things_9.setCheckable(True)
        self.CheckBox_Things_9.setObjectName("CheckBox_Things_9")
        self.gridLayout_7.addWidget(self.CheckBox_Things_9, 4, 2, 1, 1)
        self.CheckBox_Things_4 = QtWidgets.QCheckBox(self.Into_Frame_Item_5)
        font = QtGui.QFont()
        font.setPointSize(8)
        self.CheckBox_Things_4.setFont(font)
        self.CheckBox_Things_4.setText("")
        icon86 = QtGui.QIcon()
        icon86.addPixmap(QtGui.QPixmap("C:\\Albion_Progect\\Albion_Progect\\Pictures/Master\'s Heretic Cape.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.CheckBox_Things_4.setIcon(icon86)
        self.CheckBox_Things_4.setIconSize(QtCore.QSize(95, 95))
        self.CheckBox_Things_4.setCheckable(True)
        self.CheckBox_Things_4.setObjectName("CheckBox_Things_4")
        self.gridLayout_7.addWidget(self.CheckBox_Things_4, 3, 0, 1, 1)
        self.CheckBox_Things_10 = QtWidgets.QCheckBox(self.Into_Frame_Item_5)
        font = QtGui.QFont()
        font.setPointSize(8)
        self.CheckBox_Things_10.setFont(font)
        self.CheckBox_Things_10.setText("")
        icon87 = QtGui.QIcon()
        icon87.addPixmap(QtGui.QPixmap("C:\\Albion_Progect\\Albion_Progect\\Pictures/Master\'s Fort Sterling Cape.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.CheckBox_Things_10.setIcon(icon87)
        self.CheckBox_Things_10.setIconSize(QtCore.QSize(95, 95))
        self.CheckBox_Things_10.setCheckable(True)
        self.CheckBox_Things_10.setObjectName("CheckBox_Things_10")
        self.gridLayout_7.addWidget(self.CheckBox_Things_10, 5, 0, 1, 1)
        self.CheckBox_Things_2 = QtWidgets.QCheckBox(self.Into_Frame_Item_5)
        font = QtGui.QFont()
        font.setPointSize(8)
        self.CheckBox_Things_2.setFont(font)
        self.CheckBox_Things_2.setText("")
        icon88 = QtGui.QIcon()
        icon88.addPixmap(QtGui.QPixmap("C:\\Albion_Progect\\Albion_Progect\\Pictures/Master\'s Satchel of Insight@0.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.CheckBox_Things_2.setIcon(icon88)
        self.CheckBox_Things_2.setIconSize(QtCore.QSize(95, 95))
        self.CheckBox_Things_2.setCheckable(True)
        self.CheckBox_Things_2.setObjectName("CheckBox_Things_2")
        self.gridLayout_7.addWidget(self.CheckBox_Things_2, 1, 1, 1, 1)
        self.CheckBox_Things_13 = QtWidgets.QCheckBox(self.Into_Frame_Item_5)
        font = QtGui.QFont()
        font.setPointSize(8)
        self.CheckBox_Things_13.setFont(font)
        self.CheckBox_Things_13.setText("")
        icon89 = QtGui.QIcon()
        icon89.addPixmap(QtGui.QPixmap("C:\\Albion_Progect\\Albion_Progect\\Pictures/Master\'s Martlock Cape.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.CheckBox_Things_13.setIcon(icon89)
        self.CheckBox_Things_13.setIconSize(QtCore.QSize(95, 95))
        self.CheckBox_Things_13.setCheckable(True)
        self.CheckBox_Things_13.setObjectName("CheckBox_Things_13")
        self.gridLayout_7.addWidget(self.CheckBox_Things_13, 6, 0, 1, 1)
        self.CheckBox_Things_3 = QtWidgets.QCheckBox(self.Into_Frame_Item_5)
        font = QtGui.QFont()
        font.setPointSize(8)
        self.CheckBox_Things_3.setFont(font)
        self.CheckBox_Things_3.setText("")
        icon90 = QtGui.QIcon()
        icon90.addPixmap(QtGui.QPixmap("C:\\Albion_Progect\\Albion_Progect\\Pictures/Master\'s Cape.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.CheckBox_Things_3.setIcon(icon90)
        self.CheckBox_Things_3.setIconSize(QtCore.QSize(95, 95))
        self.CheckBox_Things_3.setCheckable(True)
        self.CheckBox_Things_3.setObjectName("CheckBox_Things_3")
        self.gridLayout_7.addWidget(self.CheckBox_Things_3, 1, 2, 1, 1)
        self.CheckBox_Things_1 = QtWidgets.QCheckBox(self.Into_Frame_Item_5)
        font = QtGui.QFont()
        font.setPointSize(8)
        self.CheckBox_Things_1.setFont(font)
        self.CheckBox_Things_1.setText("")
        icon91 = QtGui.QIcon()
        icon91.addPixmap(QtGui.QPixmap("C:\\Albion_Progect\\Albion_Progect\\Pictures/Master\'s Bag.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.CheckBox_Things_1.setIcon(icon91)
        self.CheckBox_Things_1.setIconSize(QtCore.QSize(95, 95))
        self.CheckBox_Things_1.setCheckable(True)
        self.CheckBox_Things_1.setObjectName("CheckBox_Things_1")
        self.gridLayout_7.addWidget(self.CheckBox_Things_1, 1, 0, 1, 1)
        self.CheckBox_Things_14= QtWidgets.QCheckBox(self.Into_Frame_Item_5)
        font = QtGui.QFont()
        font.setPointSize(8)
        self.CheckBox_Things_14.setFont(font)
        self.CheckBox_Things_14.setText("")
        icon92 = QtGui.QIcon()
        icon92.addPixmap(QtGui.QPixmap("C:\\Albion_Progect\\Albion_Progect\\Pictures/Master\'s Thetford Cape.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.CheckBox_Things_14.setIcon(icon92)
        self.CheckBox_Things_14.setIconSize(QtCore.QSize(95, 95))
        self.CheckBox_Things_14.setCheckable(True)
        self.CheckBox_Things_14.setObjectName("CheckBox_Things_14")
        self.gridLayout_7.addWidget(self.CheckBox_Things_14, 6, 2, 1, 1)
        self.CheckBox_Things_12 = QtWidgets.QCheckBox(self.Into_Frame_Item_5)
        font = QtGui.QFont()
        font.setPointSize(8)
        self.CheckBox_Things_12.setFont(font)
        self.CheckBox_Things_12.setText("")
        icon93 = QtGui.QIcon()
        icon93.addPixmap(QtGui.QPixmap("C:\\Albion_Progect\\Albion_Progect\\Pictures/Master\'s Bridgewatch Cape.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.CheckBox_Things_12.setIcon(icon93)
        self.CheckBox_Things_12.setIconSize(QtCore.QSize(95, 95))
        self.CheckBox_Things_12.setCheckable(True)
        self.CheckBox_Things_12.setObjectName("CheckBox_Things_12")
        self.gridLayout_7.addWidget(self.CheckBox_Things_12, 5, 2, 1, 1)
        self.CheckBox_Things_11 = QtWidgets.QCheckBox(self.Into_Frame_Item_5)
        font = QtGui.QFont()
        font.setPointSize(8)
        self.CheckBox_Things_11.setFont(font)
        self.CheckBox_Things_11.setText("")
        icon94 = QtGui.QIcon()
        icon94.addPixmap(QtGui.QPixmap("C:\\Albion_Progect\\Albion_Progect\\Pictures/Master\'s Lymhurst Cape.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.CheckBox_Things_11.setIcon(icon94)
        self.CheckBox_Things_11.setIconSize(QtCore.QSize(95, 95))
        self.CheckBox_Things_11.setCheckable(True)
        self.CheckBox_Things_11.setObjectName("CheckBox_Things_11")
        self.gridLayout_7.addWidget(self.CheckBox_Things_11, 5, 1, 1, 1)
        self.Main_Frame_Item.addTab(self.Bags, "")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.Into_Frame_Item_6 = QtWidgets.QFrame(self.tab)
        self.Into_Frame_Item_6.setGeometry(QtCore.QRect(0, 0, 425, 780))
        self.Into_Frame_Item_6.setObjectName("Into_Frame_Item_6")
        self.gridLayout_8 = QtWidgets.QGridLayout(self.Into_Frame_Item_6)
        self.gridLayout_8.setObjectName("gridLayout_8")
        self.CheckBox_Res_D_3 = QtWidgets.QCheckBox(self.Into_Frame_Item_6)
        font = QtGui.QFont()
        font.setPointSize(8)
        self.CheckBox_Res_D_3.setFont(font)
        self.CheckBox_Res_D_3.setText("")
        icon95 = QtGui.QIcon()
        icon95.addPixmap(QtGui.QPixmap("C:\\Albion_Progect\\Albion_Progect\\Pictures/Bloodoak Planks.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.CheckBox_Res_D_3.setIcon(icon95)
        self.CheckBox_Res_D_3.setIconSize(QtCore.QSize(100, 100))
        self.CheckBox_Res_D_3.setCheckable(True)
        self.CheckBox_Res_D_3.setObjectName("CheckBox_Res_D_3")
        self.gridLayout_8.addWidget(self.CheckBox_Res_D_3, 3, 1, 1, 1, QtCore.Qt.AlignHCenter)
        self.CheckBox_Res_D_2 = QtWidgets.QCheckBox(self.Into_Frame_Item_6)
        font = QtGui.QFont()
        font.setPointSize(8)
        self.CheckBox_Res_D_2.setFont(font)
        self.CheckBox_Res_D_2.setText("")
        icon96 = QtGui.QIcon()
        icon96.addPixmap(QtGui.QPixmap("C:\\Albion_Progect\\Albion_Progect\\Pictures/Lavish Cloth.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.CheckBox_Res_D_2.setIcon(icon96)
        self.CheckBox_Res_D_2.setIconSize(QtCore.QSize(100, 100))
        self.CheckBox_Res_D_2.setCheckable(True)
        self.CheckBox_Res_D_2.setObjectName("CheckBox_Res_D_2")
        self.gridLayout_8.addWidget(self.CheckBox_Res_D_2, 1, 1, 1, 1, QtCore.Qt.AlignHCenter)
        self.CheckBox_Res_4 = QtWidgets.QCheckBox(self.Into_Frame_Item_6)
        font = QtGui.QFont()
        font.setPointSize(8)
        self.CheckBox_Res_4.setFont(font)
        self.CheckBox_Res_4.setText("")
        icon97 = QtGui.QIcon()
        icon97.addPixmap(QtGui.QPixmap("C:\\Albion_Progect\\Albion_Progect\\Pictures/Robust Hide.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.CheckBox_Res_4.setIcon(icon97)
        self.CheckBox_Res_4.setIconSize(QtCore.QSize(100, 100))
        self.CheckBox_Res_4.setCheckable(True)
        self.CheckBox_Res_4.setObjectName("CheckBox_Res_4")
        self.gridLayout_8.addWidget(self.CheckBox_Res_4, 5, 0, 1, 1, QtCore.Qt.AlignHCenter)
        self.CheckBox_Res_3 = QtWidgets.QCheckBox(self.Into_Frame_Item_6)
        font = QtGui.QFont()
        font.setPointSize(8)
        self.CheckBox_Res_3.setFont(font)
        self.CheckBox_Res_3.setText("")
        icon98 = QtGui.QIcon()
        icon98.addPixmap(QtGui.QPixmap("C:\\Albion_Progect\\Albion_Progect\\Pictures/Bloodoak Logs.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.CheckBox_Res_3.setIcon(icon98)
        self.CheckBox_Res_3.setIconSize(QtCore.QSize(100, 100))
        self.CheckBox_Res_3.setCheckable(True)
        self.CheckBox_Res_3.setObjectName("CheckBox_Res_3")
        self.gridLayout_8.addWidget(self.CheckBox_Res_3, 3, 0, 1, 1, QtCore.Qt.AlignHCenter)
        self.CheckBox_Res_2 = QtWidgets.QCheckBox(self.Into_Frame_Item_6)
        font = QtGui.QFont()
        font.setPointSize(8)
        self.CheckBox_Res_2.setFont(font)
        self.CheckBox_Res_2.setText("")
        icon99 = QtGui.QIcon()
        icon99.addPixmap(QtGui.QPixmap("C:\\Albion_Progect\\Albion_Progect\\Pictures/Amberleaf Cotton.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.CheckBox_Res_2.setIcon(icon99)
        self.CheckBox_Res_2.setIconSize(QtCore.QSize(100, 100))
        self.CheckBox_Res_2.setCheckable(True)
        self.CheckBox_Res_2.setObjectName("CheckBox_Res_2")
        self.gridLayout_8.addWidget(self.CheckBox_Res_2, 1, 0, 1, 1, QtCore.Qt.AlignHCenter)
        self.CheckBox_Res_D_1 = QtWidgets.QCheckBox(self.Into_Frame_Item_6)
        font = QtGui.QFont()
        font.setPointSize(8)
        self.CheckBox_Res_D_1.setFont(font)
        self.CheckBox_Res_D_1.setText("")
        icon100 = QtGui.QIcon()
        icon100.addPixmap(QtGui.QPixmap("C:\\Albion_Progect\\Albion_Progect\\Pictures/Runite Steel Bar.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.CheckBox_Res_D_1.setIcon(icon100)
        self.CheckBox_Res_D_1.setIconSize(QtCore.QSize(100, 100))
        self.CheckBox_Res_D_1.setCheckable(True)
        self.CheckBox_Res_D_1.setObjectName("CheckBox_Res_D_1")
        self.gridLayout_8.addWidget(self.CheckBox_Res_D_1, 0, 1, 1, 1, QtCore.Qt.AlignHCenter)
        self.CheckBox_Res_5 = QtWidgets.QCheckBox(self.Into_Frame_Item_6)
        font = QtGui.QFont()
        font.setPointSize(8)
        self.CheckBox_Res_5.setFont(font)
        self.CheckBox_Res_5.setText("")
        icon101 = QtGui.QIcon()
        icon101.addPixmap(QtGui.QPixmap("C:\\Albion_Progect\\Albion_Progect\\Pictures/Slate.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.CheckBox_Res_5.setIcon(icon101)
        self.CheckBox_Res_5.setIconSize(QtCore.QSize(100, 100))
        self.CheckBox_Res_5.setCheckable(True)
        self.CheckBox_Res_5.setObjectName("CheckBox_Res_5")
        self.gridLayout_8.addWidget(self.CheckBox_Res_5, 6, 0, 1, 1, QtCore.Qt.AlignHCenter)
        self.CheckBox_Res_1 = QtWidgets.QCheckBox(self.Into_Frame_Item_6)
        font = QtGui.QFont()
        font.setPointSize(8)
        self.CheckBox_Res_1.setFont(font)
        self.CheckBox_Res_1.setText("")
        icon102 = QtGui.QIcon()
        icon102.addPixmap(QtGui.QPixmap("C:\\Albion_Progect\\Albion_Progect\\Pictures/Runite Ore.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.CheckBox_Res_1.setIcon(icon102)
        self.CheckBox_Res_1.setIconSize(QtCore.QSize(100, 100))
        self.CheckBox_Res_1.setCheckable(True)
        self.CheckBox_Res_1.setObjectName("CheckBox_Res_1")
        self.gridLayout_8.addWidget(self.CheckBox_Res_1, 0, 0, 1, 1, QtCore.Qt.AlignHCenter)
        self.CheckBox_Res_D_4 = QtWidgets.QCheckBox(self.Into_Frame_Item_6)
        font = QtGui.QFont()
        font.setPointSize(8)
        self.CheckBox_Res_D_4.setFont(font)
        self.CheckBox_Res_D_4.setText("")
        icon103 = QtGui.QIcon()
        icon103.addPixmap(QtGui.QPixmap("C:\\Albion_Progect\\Albion_Progect\\Pictures/Hardened Leather.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.CheckBox_Res_D_4.setIcon(icon103)
        self.CheckBox_Res_D_4.setIconSize(QtCore.QSize(100, 100))
        self.CheckBox_Res_D_4.setCheckable(True)
        self.CheckBox_Res_D_4.setObjectName("CheckBox_Res_D_4")
        self.gridLayout_8.addWidget(self.CheckBox_Res_D_4, 5, 1, 1, 1, QtCore.Qt.AlignHCenter)
        self.CheckBox_Res_D_5 = QtWidgets.QCheckBox(self.Into_Frame_Item_6)
        font = QtGui.QFont()
        font.setPointSize(8)
        self.CheckBox_Res_D_5.setFont(font)
        self.CheckBox_Res_D_5.setText("")
        icon104 = QtGui.QIcon()
        icon104.addPixmap(QtGui.QPixmap("C:\\Albion_Progect\\Albion_Progect\\Pictures/Slate Block.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.CheckBox_Res_D_5.setIcon(icon104)
        self.CheckBox_Res_D_5.setIconSize(QtCore.QSize(100, 100))
        self.CheckBox_Res_D_5.setCheckable(True)
        self.CheckBox_Res_D_5.setObjectName("CheckBox_Res_D_5")
        self.gridLayout_8.addWidget(self.CheckBox_Res_D_5, 6, 1, 1, 1, QtCore.Qt.AlignHCenter)
        self.Main_Frame_Item.addTab(self.tab, "")
        self.Main_Button_Frame = QtWidgets.QFrame(self.centralwidget)
        self.Main_Button_Frame.setGeometry(QtCore.QRect(0, 150, 325, 400))
        font = QtGui.QFont()
        font.setPointSize(13)
        font.setBold(False)
        font.setWeight(50)
        self.Main_Button_Frame.setFont(font)
        self.Main_Button_Frame.setObjectName("Main_Button_Frame")
        self.gridLayout = QtWidgets.QGridLayout(self.Main_Button_Frame)
        self.gridLayout.setObjectName("gridLayout")
        self.checkBox_Chair_2 = QtWidgets.QCheckBox(self.Main_Button_Frame)
        self.checkBox_Chair_2.setObjectName("checkBox_Chair_2")
        self.gridLayout.addWidget(self.checkBox_Chair_2, 6, 1, 1, 1, QtCore.Qt.AlignHCenter)
        self.checkBox_Chair_3 = QtWidgets.QCheckBox(self.Main_Button_Frame)
        self.checkBox_Chair_3.setObjectName("checkBox_Chair_3")
        self.gridLayout.addWidget(self.checkBox_Chair_3, 7, 1, 1, 1, QtCore.Qt.AlignHCenter)
        self.Citys = QtWidgets.QLabel(self.Main_Button_Frame)
        font = QtGui.QFont()
        font.setPointSize(25)
        self.Citys.setFont(font)
        self.Citys.setObjectName("Citys")
        self.gridLayout.addWidget(self.Citys, 0, 1, 1, 1, QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter)
        self.checkBox_Tier_8 = QtWidgets.QCheckBox(self.Main_Button_Frame)
        self.checkBox_Tier_8.setObjectName("checkBox_Tier_8")
        self.gridLayout.addWidget(self.checkBox_Tier_8, 8, 0, 1, 1, QtCore.Qt.AlignHCenter)
        self.checkBox_Thetford = QtWidgets.QCheckBox(self.Main_Button_Frame)
        self.checkBox_Thetford.setObjectName("checkBox_Thetford")
        self.gridLayout.addWidget(self.checkBox_Thetford, 1, 2, 1, 1)
        self.radioButton_5 = QtWidgets.QRadioButton(self.Main_Button_Frame)
        self.radioButton_5.setObjectName("radioButton_5")
        self.gridLayout.addWidget(self.radioButton_5, 8, 2, 1, 1, QtCore.Qt.AlignHCenter)
        self.checkBox_Chair_4 = QtWidgets.QCheckBox(self.Main_Button_Frame)
        self.checkBox_Chair_4.setObjectName("checkBox_Chair_4")
        self.gridLayout.addWidget(self.checkBox_Chair_4, 8, 1, 1, 1, QtCore.Qt.AlignHCenter)
        self.radioButton_4 = QtWidgets.QRadioButton(self.Main_Button_Frame)
        self.radioButton_4.setObjectName("radioButton_4")
        self.gridLayout.addWidget(self.radioButton_4, 7, 2, 1, 1, QtCore.Qt.AlignHCenter)
        self.label_Chair = QtWidgets.QLabel(self.Main_Button_Frame)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.label_Chair.setFont(font)
        self.label_Chair.setObjectName("label_Chair")
        self.gridLayout.addWidget(self.label_Chair, 3, 1, 1, 1, QtCore.Qt.AlignHCenter)
        self.checkBox_Caerleon = QtWidgets.QCheckBox(self.Main_Button_Frame)
        self.checkBox_Caerleon.setObjectName("checkBox_Caerleon")
        self.gridLayout.addWidget(self.checkBox_Caerleon, 1, 1, 1, 1)
        self.label_Tier = QtWidgets.QLabel(self.Main_Button_Frame)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.label_Tier.setFont(font)
        self.label_Tier.setObjectName("label_Tier")
        self.gridLayout.addWidget(self.label_Tier, 3, 0, 1, 1, QtCore.Qt.AlignHCenter)
        self.checkBox_Tier_4 = QtWidgets.QCheckBox(self.Main_Button_Frame)
        self.checkBox_Tier_4.setObjectName("checkBox_Tier_4")
        self.gridLayout.addWidget(self.checkBox_Tier_4, 4, 0, 1, 1, QtCore.Qt.AlignHCenter)
        self.checkBox_Chair_1 = QtWidgets.QCheckBox(self.Main_Button_Frame)
        self.checkBox_Chair_1.setObjectName("checkBox_Chair_1")
        self.gridLayout.addWidget(self.checkBox_Chair_1, 5, 1, 1, 1, QtCore.Qt.AlignHCenter)
        self.label_Rarity = QtWidgets.QLabel(self.Main_Button_Frame)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.label_Rarity.setFont(font)
        self.label_Rarity.setObjectName("label_Rarity")
        self.gridLayout.addWidget(self.label_Rarity, 3, 2, 1, 1, QtCore.Qt.AlignHCenter)
        self.radioButton_1 = QtWidgets.QRadioButton(self.Main_Button_Frame)
        self.radioButton_1.setObjectName("radioButton_1")
        self.gridLayout.addWidget(self.radioButton_1, 4, 2, 1, 1, QtCore.Qt.AlignHCenter)
        self.checkBox_Tier_5 = QtWidgets.QCheckBox(self.Main_Button_Frame)
        self.checkBox_Tier_5.setObjectName("checkBox_Tier_5")
        self.gridLayout.addWidget(self.checkBox_Tier_5, 5, 0, 1, 1, QtCore.Qt.AlignHCenter)
        self.checkBox_Chair_0 = QtWidgets.QCheckBox(self.Main_Button_Frame)
        self.checkBox_Chair_0.setObjectName("checkBox_Chair_0")
        self.gridLayout.addWidget(self.checkBox_Chair_0, 4, 1, 1, 1, QtCore.Qt.AlignHCenter)
        self.radioButton_3 = QtWidgets.QRadioButton(self.Main_Button_Frame)
        self.radioButton_3.setObjectName("radioButton_3")
        self.gridLayout.addWidget(self.radioButton_3, 6, 2, 1, 1, QtCore.Qt.AlignHCenter)
        self.radioButton_2 = QtWidgets.QRadioButton(self.Main_Button_Frame)
        self.radioButton_2.setObjectName("radioButton_2")
        self.gridLayout.addWidget(self.radioButton_2, 5, 2, 1, 1, QtCore.Qt.AlignHCenter)
        self.checkBox_Tier_6 = QtWidgets.QCheckBox(self.Main_Button_Frame)
        self.checkBox_Tier_6.setObjectName("checkBox_Tier_6")
        self.gridLayout.addWidget(self.checkBox_Tier_6, 6, 0, 1, 1, QtCore.Qt.AlignHCenter)
        self.checkBox_Tier_7 = QtWidgets.QCheckBox(self.Main_Button_Frame)
        self.checkBox_Tier_7.setObjectName("checkBox_Tier_7")
        self.gridLayout.addWidget(self.checkBox_Tier_7, 7, 0, 1, 1, QtCore.Qt.AlignHCenter)
        self.checkBox_Martlock = QtWidgets.QCheckBox(self.Main_Button_Frame)
        self.checkBox_Martlock.setObjectName("checkBox_Martlock")
        self.gridLayout.addWidget(self.checkBox_Martlock, 2, 2, 1, 1)
        self.checkBox_Bridgewatch = QtWidgets.QCheckBox(self.Main_Button_Frame)
        self.checkBox_Bridgewatch.setObjectName("checkBox_Bridgewatch")
        self.gridLayout.addWidget(self.checkBox_Bridgewatch, 2, 1, 1, 1)
        self.checkBox_Lymhurst = QtWidgets.QCheckBox(self.Main_Button_Frame)
        self.checkBox_Lymhurst.setObjectName("checkBox_Lymhurst")
        self.gridLayout.addWidget(self.checkBox_Lymhurst, 2, 0, 1, 1)
        self.checkBox_Fort_Stearling = QtWidgets.QCheckBox(self.Main_Button_Frame)
        self.checkBox_Fort_Stearling.setObjectName("checkBox_Fort_Stearling")
        self.gridLayout.addWidget(self.checkBox_Fort_Stearling, 1, 0, 1, 1)
        self.horizontalFrame = QtWidgets.QFrame(self.centralwidget)
        self.horizontalFrame.setGeometry(QtCore.QRect(5, 600, 315, 41))
        self.horizontalFrame.setObjectName("horizontalFrame")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.horizontalFrame)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.pushButton_Start = QtWidgets.QPushButton(self.horizontalFrame)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.pushButton_Start.setFont(font)
        self.pushButton_Start.setObjectName("pushButton_Start")
        self.horizontalLayout.addWidget(self.pushButton_Start)
        self.pushButton_Exit = QtWidgets.QPushButton(self.horizontalFrame)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.pushButton_Exit.setFont(font)
        self.pushButton_Exit.setObjectName("pushButton_Exit")
        self.horizontalLayout.addWidget(self.pushButton_Exit)
        self.horizontalFrame_2 = QtWidgets.QFrame(self.centralwidget)
        self.horizontalFrame_2.setGeometry(QtCore.QRect(5, 560, 325, 50))
        self.horizontalFrame_2.setObjectName("horizontalFrame_2")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.horizontalFrame_2)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.radioButton_6 = QtWidgets.QRadioButton(self.horizontalFrame_2)
        font = QtGui.QFont()
        font.setPointSize(13)
        self.radioButton_6.setFont(font)
        self.radioButton_6.setObjectName("radioButton_6")
        self.horizontalLayout_2.addWidget(self.radioButton_6, 0, QtCore.Qt.AlignHCenter)
        self.radioButton = QtWidgets.QRadioButton(self.horizontalFrame_2)
        font = QtGui.QFont()
        font.setPointSize(13)
        self.radioButton.setFont(font)
        self.radioButton.setObjectName("radioButton")
        self.horizontalLayout_2.addWidget(self.radioButton, 0, QtCore.Qt.AlignHCenter)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        self.Main_Frame_Item.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)


        self.All_buttons_Clotch_Armor = QButtonGroup()
        self.All_buttons_Clotch_Armor.setExclusive(False)

        self.All_buttons_Leather_Armor = QButtonGroup()     
        self.All_buttons_Leather_Armor.setExclusive(False)

        self.All_buttons_Plate_Armor = QButtonGroup()
        self.All_buttons_Plate_Armor.setExclusive(False)

        self.All_tier_group = QButtonGroup()
        self.All_tier_group.setExclusive(False)

        self.All_rarity_group = QButtonGroup()
        self.All_rarity_group.setExclusive(False)

        self.All_qualities_group = QButtonGroup()

        self.All_Citys_group = QButtonGroup()
        self.All_Citys_group.setExclusive(False)

        self.All_Things_group = QButtonGroup()
        self.All_Things_group.setExclusive(False)

        self.All_Resours_group = QButtonGroup()
        self.All_Resours_group.setExclusive(False)

        for i in range(1, 15):
            self.All_Things_group.addButton(getattr(self, f"CheckBox_Things_{i}"), i - 1)

        for i in range(1, 6):
            self.All_Resours_group.addButton(getattr(self, f"CheckBox_Res_{i}"), i - 1)
            self.All_Resours_group.addButton(getattr(self, f"CheckBox_Res_D_{i}"), i + 4)

        for i in range(1, 28):
            self.All_buttons_Clotch_Armor.addButton(getattr(self, f"checkBox{i}"), i - 1)
            self.All_buttons_Leather_Armor.addButton(getattr(self, f"checkBox{i + 27}"), i - 1)
            self.All_buttons_Plate_Armor.addButton(getattr(self, f"checkBox{i + 54}"), i - 1)

        for i, checkbox in enumerate([self.checkBox_Tier_4, self.checkBox_Tier_5, self.checkBox_Tier_6, self.checkBox_Tier_7, self.checkBox_Tier_8]):
            self.All_tier_group.addButton(checkbox, i)

        for i, checkbox in enumerate([self.checkBox_Chair_0, self.checkBox_Chair_1, self.checkBox_Chair_2, self.checkBox_Chair_3, self.checkBox_Chair_4]):
            self.All_rarity_group.addButton(checkbox, i)

        for i, radio in enumerate([self.radioButton_1, self.radioButton_2, self.radioButton_3, self.radioButton_4, self.radioButton_5]):
            self.All_qualities_group.addButton(radio, i + 1)

        for i, checkbox in enumerate([self.checkBox_Caerleon, self.checkBox_Fort_Stearling, self.checkBox_Martlock, self.checkBox_Thetford, self.checkBox_Lymhurst, self.checkBox_Bridgewatch]):
            self.All_Citys_group.addButton(checkbox, i)


        self.button_funckshens()
        

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.Main_Frame_Item.setTabText(self.Main_Frame_Item.indexOf(self.Clotch), _translate("MainWindow", "Тканевая Б."))
        self.Main_Frame_Item.setTabText(self.Main_Frame_Item.indexOf(self.Kozaa), _translate("MainWindow", "Кожаная Б."))
        self.Main_Frame_Item.setTabText(self.Main_Frame_Item.indexOf(self.Lat), _translate("MainWindow", "Латная Б."))
        self.Main_Frame_Item.setTabText(self.Main_Frame_Item.indexOf(self.Bags), _translate("MainWindow", "Шмотки"))
        self.Main_Frame_Item.setTabText(self.Main_Frame_Item.indexOf(self.tab), _translate("MainWindow", "Ресурсы"))
        self.checkBox_Chair_2.setText(_translate("MainWindow", "2"))
        self.checkBox_Chair_3.setText(_translate("MainWindow", "3"))
        self.Citys.setText(_translate("MainWindow", "Город"))
        self.checkBox_Tier_8.setText(_translate("MainWindow", "8"))
        self.checkBox_Thetford.setText(_translate("MainWindow", "Thetford"))
        self.radioButton_5.setText(_translate("MainWindow", "Шедевр"))
        self.checkBox_Chair_4.setText(_translate("MainWindow", "4"))
        self.radioButton_4.setText(_translate("MainWindow", "Отличное"))
        self.label_Chair.setText(_translate("MainWindow", "Зачар"))
        self.checkBox_Caerleon.setText(_translate("MainWindow", "Caerleon"))
        self.label_Tier.setText(_translate("MainWindow", "Тир"))
        self.checkBox_Tier_4.setText(_translate("MainWindow", "4"))
        self.checkBox_Chair_1.setText(_translate("MainWindow", "1"))
        self.label_Rarity.setText(_translate("MainWindow", "Качество"))
        self.radioButton_1.setText(_translate("MainWindow", "Обычное"))
        self.checkBox_Tier_5.setText(_translate("MainWindow", "5"))
        self.checkBox_Chair_0.setText(_translate("MainWindow", "0"))
        self.radioButton_3.setText(_translate("MainWindow", "Выдающ"))
        self.radioButton_2.setText(_translate("MainWindow", "Хорошое"))
        self.checkBox_Tier_6.setText(_translate("MainWindow", "6"))
        self.checkBox_Tier_7.setText(_translate("MainWindow", "7"))
        self.checkBox_Martlock.setText(_translate("MainWindow", "Martlok"))
        self.checkBox_Bridgewatch.setText(_translate("MainWindow", "Bridgewatch"))
        self.checkBox_Lymhurst.setText(_translate("MainWindow", "Lymhurst"))
        self.checkBox_Fort_Stearling.setText(_translate("MainWindow", "Fort Stearling"))
        self.pushButton_Start.setText(_translate("MainWindow", "Start"))
        self.pushButton_Exit.setText(_translate("MainWindow", "Exit"))
        self.radioButton_6.setText(_translate("MainWindow", "Open in Browzer"))
        self.radioButton.setText(_translate("MainWindow", "Open in Data"))


    def button_funckshens(self):

        self.main_button(self.All_buttons_Clotch_Armor, List_item.Clotch_Armor)
        self.main_button(self.All_buttons_Leather_Armor, List_item.Leather_Armor)
        self.main_button(self.All_buttons_Plate_Armor, List_item.Plate_Armor)

        self.main_button(self.All_Things_group, List_item.Things)
        self.main_button(self.All_Resours_group, List_item.Resource)
        
        self.All_tier_group.buttonClicked[int].connect(self.__tier_add)
        self.All_rarity_group.buttonClicked[int].connect(self.__Rarity_add)
        self.All_qualities_group.buttonClicked[int].connect(self.__Qualities_changing)
        self.All_Citys_group.buttonClicked[int].connect(self.__City_add)

        self.pushButton_Start.clicked.connect(lambda: self.New_start())
        self.pushButton_Exit.clicked.connect(lambda: self.exit())
        
        
    def main_button(self, group_button: list, item_list: list):
        global Item_list_f
        
        def check_butt(butt_id):
            #Получение id кнопки
            for btn in group_button.buttons():
                if btn is group_button.button(butt_id):
                    
                    #Добавление предмета в список
                    if item_list[butt_id] in Item_list_f: 
                        Item_list_f.remove(item_list[butt_id])
                    #Удаление предмета со списка
                    else: 
                        Item_list_f.append(item_list[butt_id])
                        
        group_button.buttonClicked[int].connect(check_butt)


    def end_list(self, item_list_f, tier_list, rarity_list):
        item_list_new = []
        Res_list = List_item.Resource

        for item in item_list_f:
            for tier in tier_list:
                for rarity in rarity_list:

                    if item != 'STONEBLOCK':
                        item_list_new.append(tier + item + rarity)
                    else:
                        item_list_new.append(tier + item)


        def rename(string:str):
            if string[-2:] == "@1":
                return string[:-2] + "_LEVEL1@1"
            elif string[-2:] == "@2":
                return string[:-2] + "_LEVEL2@2"
            elif string[-2:] == "@3":
                return string[:-2] + "_LEVEL3@3"
            elif string[-2:] == "@4":
                return string[:-2] + "_LEVEL4@4"
            else:
                return string
            
        def trim_string(string:str):
            if string[-2] == "@":
                return string[3:-2]
            else:
                return string[3:]


        for i in range(len(item_list_new)):
            item = item_list_new[i]
            if trim_string(item) in Res_list:
                item_list_new[i] = rename(item)
                
        return item_list_new


    def __tier_add(self, button_id: int):

        for btn in self.All_tier_group.buttons():
            if btn is self.All_tier_group.button(button_id):

                if Tiers[button_id] in Tier_list:
                    Tier_list.remove(Tiers[button_id])
                else:
                    Tier_list.append(Tiers[button_id])
                Tier_list.sort()


    def __Rarity_add(self, button_id: int):

        for btn in self.All_rarity_group.buttons():
            if btn is self.All_rarity_group.button(button_id):

                if Rarytyes[button_id] in Rarity_list:
                    Rarity_list.remove(Rarytyes[button_id])
                else:
                    Rarity_list.append(Rarytyes[button_id])
                Rarity_list.sort()


    def __City_add(self, button_id: int):
        global locations_list
        for btn in self.All_Citys_group.buttons():
            if btn is self.All_Citys_group.button(button_id):

                if locations[button_id] in locations_list:
                    locations_list.remove(locations[button_id])
                    locations_list.sort()
                else:
                    locations_list.append(locations[button_id])
                    locations_list.sort()


    def __Qualities_changing(self, button_id: int):
        global qualities
        qualities = button_id


    def Save_Json_From_Url(self, url: str, parse_date_column: str, pretty_print=False):
        try:
            df = pandas.read_html(url, header=0, parse_dates=[parse_date_column])
        except Exception as e:
            print(f"Failed to read data from {url}: {e}")
            
        current_time = datetime.now().strftime("%Y-%m-%d %H-%M-%S")
        
        file_name = f"Prices_{current_time}.json"

        path_to_save = './Last_List_Fille/'
        
        if os.path.isfile(file_name):   # Проверяем, существует ли уже файл
            print(f"File {file_name} already exists, will not overwrite")
            return
        
        try:    # Записываем данные в формате JSON в файл с указанным именем
            df[0].to_json(path_to_save + file_name, date_format="iso", indent=4 if pretty_print else None)
            print(f"Data saved to {file_name}")
        except Exception as e:  # Выводим сообщение об ошибке, если сохранение не удалось
            print(f"Failed to save data to {file_name}: {e}")


    def New_start(self):

        if self.radioButton.isChecked() and len(Tier_list) == 0 and len(Rarity_list) == 0 and len(locations_list) == 0: 
            self.Open_Program() 
        else:
            if all(len(lst) > 0 for lst in [Item_list_f, Tier_list, Rarity_list, locations_list]):
                
                data = {    # Создаем словарь данных, которые нужно сохранить
                    'items': Item_list_f,
                    'tiers': Tier_list,
                    'rarities': Rarity_list,
                    'locations': locations_list,
                    'qualities': qualities
                    }
                
                with open('Last_Lists.json', 'w') as file:
                    json.dump(data, file, indent=4)

                # Создаем URL на основе данных из списков и других параметров
                URL = stock + ','. join(self.end_list(Item_list_f, Tier_list, Rarity_list)) + location + ','. join(locations_list) + qualities_url + str(qualities)

                if self.radioButton_6.isChecked(): 
                    webbrowser.open_new(URL)
                
                # Сохраняем данные в файле с помощью метода Save_Json_From_Url
                self.Save_Json_From_Url(URL, 'item_id', True) 

                if self.radioButton.isChecked(): 
                    self.Open_Program()


    def exit(self):
        sys.exit()


stock = 'https://www.albion-online-data.com/api/v2/stats/view/'
location = '?locations='
qualities_url = '&qualities='

locations = ['Caerleon','Fortsterling','Martlock','Thetford','Lymhurst','Bridgewatch']
locations_list = ['BlackMarket']

Item_list_f = []
Item_list_s = []

Tier_list = []
Rarity_list = []

Tiers = ['T4_', 'T5_', 'T6_', 'T7_', 'T8_']
Rarytyes = ['', '@1', '@2', '@3', '@4']



if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
